/-
  W-CONSTRUCTION-1 act 3 — GlobalSection.lean: act 1's global object STATED in Lean.
  Mathlib holds the TOPOLOGICAL RestrictedProduct (grep-checked: Topology/Algebra/
  RestrictedProduct, FiniteAdeleRing) but NOT the Hilbert-space restricted tensor
  product — so the object is a DECLARED structure with its existence the single
  labeled infrastructure debt. The one-line consequences are PROVED from the fields.
  Nothing at complete roster; sorries counted, labeled.
-/
import Mathlib.Analysis.InnerProductSpace.Projection.Basic
import Mathlib.LinearAlgebra.PiTensorProduct

open scoped InnerProductSpace

namespace GlobalSection

/-- ACT 16, THE EXACT MISSING LEMMA (the infrastructure debt SHARPENED, stated over
    Mathlib's algebraic `PiTensorProduct`): on the RESTRICTED SPAN — the submodule
    generated by pure tensors equal to the unit at all but finitely many places — the
    pre-inner-product determined by the finite product of local pairings is
    well-defined and positive semidefinite (an `InnerProductSpace.Core` exists).
    Mathlib holds the algebraic `PiTensorProduct` and NO inner product on it; the
    well-definedness genuinely needs the restricted span (the unrestricted product of
    pairings diverges). OWNER: infrastructure (the owner unchanged; the statement
    sharpened from `globalSectionData_exists`'s broad form). The sorry STANDS —
    THE LEDGER: 3 → 4, said plainly. -/
theorem restrictedTensor_innerCore_exists
    (ι : Type) (H : ι → Type) [∀ i, NormedAddCommGroup (H i)]
    [∀ i, InnerProductSpace ℂ (H i)] (unit : ∀ i, H i)
    (hunit : ∀ i, ‖unit i‖ = 1) :
    Nonempty (InnerProductSpace.Core ℂ
      (Submodule.span ℂ {z : PiTensorProduct ℂ H |
        ∃ x : ∀ i, H i, {i | x i ≠ unit i}.Finite ∧
          z = PiTensorProduct.tprod ℂ x})) := by
  sorry

/-- THE GLOBAL SECTION as data: a Hilbert space with a unitary `F` and `parity`,
    `F² = parity`, `parity² = 1` — the abstract shape act 1 proved the restricted
    tensor product carries (the `E₁`-units make `⊗F_v` well-defined; `F² = ⊗Π_v`).
    The CONSTRUCTION of this data as `⊗′_v S̄_v` is the infrastructure debt. -/
structure GlobalSectionData where
  H : Type
  [ncg : NormedAddCommGroup H]
  [ips : InnerProductSpace ℂ H]
  F : H ≃ₗᵢ[ℂ] H
  parity : H ≃ₗᵢ[ℂ] H
  F_sq : ∀ x, F (F x) = parity x
  parity_sq : ∀ x, parity (parity x) = x

attribute [instance] GlobalSectionData.ncg GlobalSectionData.ips

/-- `F⁴ = 1` on the global section — PROVED from the fields, no sorry. -/
theorem F_pow_four (D : GlobalSectionData) (x : D.H) :
    D.F (D.F (D.F (D.F x))) = x := by
  rw [D.F_sq, D.F_sq, D.parity_sq]

/-- the pairing is the squared norm on the fixed sector — PROVED (one line, via the
    LocalLimit abstract theorem's argument), no sorry. -/
theorem inner_F_self_of_fixed (D : GlobalSectionData) (x : D.H) (hx : D.F x = x) :
    ⟪x, D.F x⟫_ℂ = (‖x‖ : ℂ) ^ 2 := by
  rw [hx, inner_self_eq_norm_sq_to_K]
  norm_cast

/-- OWED TO INFRASTRUCTURE (the Hilbert restricted tensor product over the places, with
    `E₁`-units — Mathlib holds only the topological `RestrictedProduct`): the
    construction of the data. This is the file's single labeled sorry.
    ACT-5 CONSTRUCTION PATH, spelled so the debt is priced, not vague:
    (i) index by places, local space = the completed Sonin limit, unit = the E₁ vector
        (act 1's forced witness tensors);
    (ii) the algebraic restricted tensor product as the colimit of finite tensor
        products along unit-inclusions (Mathlib holds the finite `TensorProduct` and
        the topological `RestrictedProduct`, NOT this colimit with inner products);
    (iii) the inner product on the colimit (almost-all factors pair unit-against-unit
        to 1), then Hilbert completion.
    Steps (ii)-(iii) are the missing Mathlib infrastructure. The sorry STANDS. -/
theorem globalSectionData_exists : Nonempty GlobalSectionData := by
  sorry

end GlobalSection

#print axioms GlobalSection.F_pow_four
#print axioms GlobalSection.inner_F_self_of_fixed
#print axioms GlobalSection.globalSectionData_exists
#print axioms GlobalSection.restrictedTensor_innerCore_exists
