# -*- coding: utf-8 -*-
"""b329_correspondence.py -- FIVE ROWS, ONE PER COMPONENT, EVERY THEOREM NAMED WITH ITS GENERALITY.

### ### **THE NOTATION GUARD AND THE BLANK-CELL AUDIT ARE IMPORTED, NEVER COPIED.** ### The theorem names
### and their scope words are read from the module's own source; the profile counts are read from the
### kernel run file `b329_kernel_run.txt`. ### Nothing here is typed from memory of a run.
### ### **THE HAZARD:** ### a row that reads as "the finite side's silence is proved" -- it is proved
### GENERAL for the scaling part and PER CELL for the compact part, and every row says which.
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import b302_correspondence as C   # noqa: E402
import b303_correspondence as G   # noqa: E402

SIDE = r'D:\SIDE-global-section'
TABLE = os.path.join(SIDE, 'CORRESPONDENCE.md')
MODULE = os.path.join(SIDE, 'Core', 'FiniteSideSeal.lean')
D = os.path.join(ROOT, 'data')
KRUN = os.path.join(D, 'b329_kernel_run.txt')

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')


def read_module():
    """### theorem name -> scope word from its docstring (GENERAL / PER CELL / EXHAUSTIVENESS / Helper)."""
    src = io.open(MODULE, encoding='utf-8').read()
    out = []
    # ### the docstring group may not run past its own closing `-/` (the first draft's did, and swallowed a def's
    # ### docstring together with a section comment ahead of `mul_assoc'`; that run is kept as b329_corr_run.txt).
    for m in re.finditer(r'/--((?:(?!-/).)*?)-/\s*(?:set_option[^\n]*\n\s*)?theorem\s+([A-Za-z_][A-Za-z0-9_\']*)', src, re.S):
        doc, name = m.group(1), m.group(2)
        first = doc.strip().split('.')[0]
        if first.startswith('GENERAL'):
            scope = 'GENERAL'
        elif first.startswith('PER CELL'):
            scope = 'PER CELL'
        elif first.startswith('EXHAUSTIVENESS'):
            scope = 'EXHAUSTIVENESS'
        elif first.startswith('Helper'):
            scope = 'helper'
        else:
            scope = '?'
        out.append((name, scope))
    return out


def read_kernel():
    txt = io.open(KRUN, encoding='utf-8').read()
    m = re.search(r'prints before -> after\s*:\s*(\d+) -> (\d+)\s+zero-axiom: (\d+) -> (\d+)\s+other: (\d+) -> (\d+)', txt)
    pre = 'TRUE BYTE PREFIX OF THE NEW ONE : True' in txt
    base = 'BYTE-IDENTICAL to banked : True' in txt
    t = re.search(r'terminals printed\s*:\s*(\d+), (\d+) zero-axiom, (\d+) otherwise', txt)
    return dict(before=int(m.group(1)), after=int(m.group(2)), z0=int(m.group(3)), z1=int(m.group(4)),
                o0=int(m.group(5)), o1=int(m.group(6)), prefix=pre, baseline=base,
                nm=int(t.group(1)), zm=int(t.group(2)), om=int(t.group(3)))


def names(thms, scope, group):
    return ', '.join('`B329.%s` (%s)' % (n, s) for n, s in thms if n in group and (scope is None or s == scope))


C1 = ['valuation_exists', 'valuation_unique', 'exponent_below_level', 'index_decomposes', 'action_factors']
C2 = ['geom_identity', 'scaling_shift_inverse', 'scaling_congruence_forces_ball', 'scaling_fixed_point_in_ball',
      'scaling_fixes_nothing_off_ball', 'identity_fixes_every_index', 'unit_fixes_offball_at_cells',
      'some_unit_fixes_offball_above_level_one', 'no_unit_fixes_offball_at_level_one']
C3 = ['compact_smear_vanishes_at_cells', 'identity_trace_is_the_dimension', 'traces_not_all_zero_off_identity']
C4 = ['finite_side_silence']
HELP = ["mul_assoc'", "pow_add'", "add_right_cancel'", "add_left_cancel'", 'multiple_of_add_multiple', 'search']

SCOPE_TAIL = ("**SCOPE: A KERNEL BUILD OF BANKED DERIVATIONS, AT A FINITE PLACE, ON THIS OBJECT, IN THIS MODEL.** NOTHING "
              "ABOUT THE ARCHIMEDEAN PLACE. NOT A VERDICT ON M-2 AND NOT A DECISION ON b262's BRANCH. NO GRADE MOVED; NO ACT "
              "RE-VERDICTED. NO AGGREGATION IS STATED; M-2 REMAINS (SPECIFIED-NOT-STATED) under b310's cap. The seam's debt "
              "item 1 restated, still unpaid. The patent lane carried on the patent seat's report, UNCONFIRMED on this seat's "
              "record. h2 stands exactly where the deposit left it. NOTHING DEPOSITS.")


def rows():
    thms = read_module()
    k = read_kernel()
    prof = ("**THE PROFILE MOVED %d → %d PRINTS, ALL ZERO-AXIOM (%d → %d zero-axiom, %d → %d otherwise)**, the baseline "
            "regenerated BYTE-IDENTICALLY (%s) before anything was added and the banked profile a TRUE BYTE PREFIX of the new "
            "one (%s); the module alone printed %d terminals, %d zero-axiom, %d otherwise; `import`, `lemma`, `native_decide`, "
            "`sorry`, `axiom` each 0 in its code."
            % (k['before'], k['after'], k['z0'], k['z1'], k['o0'], k['o1'], k['baseline'], k['prefix'], k['nm'], k['zm'], k['om']))
    return [
        ("THE FINITE-SIDE SEAL, COMPONENT 1 -- THE DECOMPOSITION, GENERAL (b329)",
         "THE FINITE-SIDE SEAL, COMPONENT 1 -- THE DECOMPOSITION, GENERAL (b329): every nonzero index modulo a power of "
         "`p ≥ 2` is uniquely a non-multiple of `p` times a power of `p`, with the exponent below the level, and multiplication "
         "by the index factors through the two parts -- b304's split of the local multiplicative group into compact and scaling "
         "parts, on the model's indices, compiled: %s. **GENERAL over every base `p ≥ 2`, level, exponent and index, by strong "
         "induction and a bounded search (`B329.search`) that decides divisibility with `Nat.decEq`.** \"`p` does not divide "
         "`u`\" is `NotDiv p u := ∀ c, u ≠ p * c`. **THE REGISTERED COPRIMALITY FORM OF \"UNIT\" (T1.4) IS NOT COMPILED AND "
         "SAID**: `Nat.Coprime`'s lemmas carry `propext` (measured, `data/b329_axiom_probe.txt`); primality is used nowhere in "
         "the module, and the identification of a non-multiple of a prime with a unit of `Z/p^k` is the library's, uncompiled."
         % names(thms, None, C1),
         "**TERMINALS, ZERO AXIOMS**, `Core/FiniteSideSeal.lean`, vanilla Lean, no imports, `theorem` never `lemma`, no "
         "`native_decide`, no `sorry`; the helpers %s proved by induction because the library's `Nat.mul_assoc` and the "
         "cancellation lemmas carry `propext`." % names(thms, None, HELP),
         prof,
         "**GENERAL, AND THE ROW SAYS SO.** The exhaustiveness statement's foundation: every multiplicative action on the "
         "model's indices factors through the two parts. NO GRADE MOVED.",
         SCOPE_TAIL, "current"),

        ("THE FINITE-SIDE SEAL, COMPONENT 2 -- THE SCALING PART'S SILENCE, GENERAL, WITH ITS POLARITY CONTROLS (b329)",
         "THE FINITE-SIDE SEAL, COMPONENT 2 -- THE SCALING PART'S SILENCE, GENERAL, WITH ITS POLARITY CONTROLS (b329): "
         "`p^j - 1` is invertible modulo every `p^m` with the inverse exhibited as a geometric sum (`p^j * S + 1 = S + p^m * c`), "
         "so the fixed-point congruence of `t → p^j t` -- written with its witness, `p^j * t = t + p^m * c` -- forces the index "
         "into the ball, in either congruence; in the model's form an index `t < p^(2n)` fixed modulo the grid is in the ball. "
         "b309's mechanism, *\"the scaling map has no fixed point off the ball, in either congruence, because `p^j - 1` is "
         "invertible\"*, compiled as the law B309's header called uncompiled: %s. **THE POLARITY CONTROLS BESIDE IT, BOTH "
         "ARMS**: the identity fixes every index (GENERAL); a non-identity UNIT fixing an off-ball index exists at the "
         "level-two-and-above cells (`9` fixes `2` at `(2,2)`, `28` fixes `3` at `(3,2)`, `17` fixes `4` at `(2,3)`) and none at "
         "the level-one cells -- PER CELL, decided: %s. So the ball-forcing is the scaling map's and not every map's."
         % (names(thms, 'GENERAL', C2), names(thms, 'PER CELL', C2)),
         "**TERMINALS, ZERO AXIOMS**, same module. The registered `Nat.Coprime` form of (T2.1) is not compiled (its lemmas "
         "carry `propext`); the explicit inverse is the same fact with its witness, and the row says so.",
         prof,
         "**GENERAL over every base, level, power and index -- and the row says so.** b309's seven-cell terminal is now the "
         "instance list of a compiled law. NO GRADE MOVED.",
         SCOPE_TAIL, "current"),

        ("THE FINITE-SIDE SEAL, COMPONENT 3 -- THE COMPACT PART'S SILENCE, PER CELL (b329)",
         "THE FINITE-SIDE SEAL, COMPONENT 3 -- THE COMPACT PART'S SILENCE, PER CELL (b329): at each of the banked cells "
         "`(2,1), (2,2), (3,1), (3,2), (5,1), (7,1), (2,3)` the compressed smear over the units vanishes, "
         "`q * SUM_u A_N(u) = SUM_u A_q(u)` -- b304's zero for the constant test function on the units, in b310's signed-count "
         "form -- decided as exact arithmetic over the explicit lists; beside it the NOT-DEAD witness (the signed count at the "
         "identity is `q (p^n - 1)^2`, b310's terminal restated) and b304's own refusal decided (some non-identity unit has a "
         "nonzero signed trace at every listed cell): %s. **PER CELL, AND THE ROW SAYS SO: decided over `cells` and no other.** "
         "b304 tabulated six cells; the seventh is b309/b310's, decided by the same arithmetic -- a check added, not a claim "
         "added. **THE UNAVAILABLE ARM, STATED IN THE MODULE HEADER AND NOT MANUFACTURED**: a cell at which the constant smear "
         "SURVIVES cannot be exhibited because b304's derivation forbids it at every `p` and `n`; no control can exist there."
         % names(thms, None, C3),
         "**TERMINALS, ZERO AXIOMS**, same module, by `decide` (with `maxRecDepth` raised for the largest cell's lists).",
         prof,
         "**PER CELL, NOT GENERAL, AND WHY (in the header): the general zero is orthogonality of the object's space to the "
         "valuation shells -- linear algebra over a cyclotomic field, not vanilla-decidable -- and a general proof of the "
         "integer identity would be new mathematics, forbidden to this act.** NO GRADE MOVED.",
         SCOPE_TAIL, "current"),

        ("THE FINITE-SIDE SEAL, COMPONENT 4 -- EXHAUSTIVENESS, ONE THEOREM WHOSE HYPOTHESES NAME THE GENERALITY (b329)",
         "THE FINITE-SIDE SEAL, COMPONENT 4 -- EXHAUSTIVENESS, ONE THEOREM WHOSE HYPOTHESES NAME THE GENERALITY (b329): "
         "%s -- for `p ≥ 2`, a level `n` and an index `0 < t < p^(2n)`: (a) GENERAL, `t = u * p^j` with `j < 2n` and `p` not "
         "dividing `u`; (b) GENERAL, for every `j > 0` a fixed point of `t → p^j t` modulo the grid, with its witness, is in "
         "the ball; (c) PER CELL, if `(p, n)` is in `cells` then `q * SUM_u A_N(u) = SUM_u A_q(u)`, the cell list as the "
         "hypothesis. Its docstring quotes b310 from its emitting act: *\"`Tr(theta(t) Pi)` IS A SIGNED COUNT OF THE OFF-BALL "
         "POINTS `t` FIXES, IN THE TWO CONGRUENCES THE OBJECT'S TWO CONDITIONS IMPOSE, WEIGHTED BY THE EMBEDDING'S HAAR "
         "FACTOR.\"* **THE COUNTING FORM IS WHAT IS COMPILED; THE IDENTIFICATION OF THAT COUNT WITH THE SOURCE'S TRACE IS "
         "b310's DERIVATION AND IS NOT.**" % names(thms, None, C4),
         "**ONE TERMINAL, ZERO AXIOMS**, same module; (a) and (b) from Components 1 and 2, (c) by `decide` at each listed cell "
         "after the membership hypothesis is split.",
         prof,
         "**THE GENERAL AND THE PER-CELL KEPT APART IN ONE STATEMENT** -- the arms carry their own words. The lore gains "
         "*general and per-cell are stated in the module header, never averaged* with its gate (`b329_header_gate`). NO GRADE "
         "MOVED.",
         SCOPE_TAIL, "current"),

        ("THE FINITE-SIDE SEAL, COMPONENT 5 -- THE PROFILE, THE COVERAGE GATE, AND THE LEDGER (b329)",
         "THE FINITE-SIDE SEAL, COMPONENT 5 -- THE PROFILE, THE COVERAGE GATE, AND THE LEDGER (b329): the module imported by "
         "`AllPrints.lean` in the same commit (the import after the last import, the prints at the END, written by the kernel "
         "tool so neither can land without the other); %s The coverage gate (`b315_coverage_gate.py`) after the build: modules "
         "with a print target and not imported 0, print targets not in the profile 0. The faces ledger's F5 row (the fixed-point "
         "silence) updated through the writer's `append_block` to **PROVED-GENERAL for the scaling part and PROVED-AT-CELLS for "
         "the compact part**, the row above never rewritten." % prof,
         "**NO TERMINAL OF ITS OWN.** The profile is the act's evidence of compile; a claimed compile is reported only from it.",
         "**THE AXIOM FINDING, DECLARED**: the core library's `∣`, `%`, `/` and `Nat.Coprime` lemmas -- and `Nat.mul_assoc` -- "
         "carry `propext`/`Quot.sound`, as do `omega`, `simp`, `ac_rfl` and `by_cases` on divisibility (measured at "
         "`data/b329_axiom_probe.txt`); the first draft's general proofs printed `[propext, Quot.sound]` and were rewritten as "
         "equations with witnesses before any profile was written.",
         "**A BUILD IS NOT A VERDICT.** What the terminals certify is the arithmetic of the model and the counting form of the "
         "trace, general where the header says general and per cell where it says per cell. NO GRADE MOVED.",
         SCOPE_TAIL, "current"),
    ]


def main():
    ROWS = rows()
    txt = io.open(TABLE, encoding='utf-8').read()
    pos, neg = C.blank_check_fixture()
    sa, sb, sc, sd = G.split_fixture()
    print('=' * 100)
    print("b329 -- THE FINITE-SIDE SEAL. ### THE ROWS, ONE PER COMPONENT, EVERY THEOREM NAMED WITH ITS SCOPE.")
    print('=' * 100)
    print('  BLANK-CHECK FIXTURE (imported from b302): real blank=%s  quiet on full=%s  %s' % (pos, neg, 'PASS' if (pos and neg) else '### FAIL ###'))
    print('  SPLITTER FIXTURE (imported from b303): plain=%s escaped=%s content=%s raw=%s  %s' % (sa, sb, sc, sd, 'PASS' if (sa and sb and sc and sd) else '### FAIL ###'))
    if not (pos and neg and sa and sb and sc and sd):
        return 1
    thms = read_module()
    print('  theorems read from the module : %d ; scope words : %s' % (len(thms), sorted(set(s for _n, s in thms))))
    unknown = [n for n, s in thms if s == '?']
    print('  theorems without a scope word in their docstring : %d %s' % (len(unknown), unknown if unknown else ''))
    if unknown:
        return 1
    print('  blank cells in the whole table (line-scoped) : %d' % C.blank_cells(txt))
    bad = [(i, j) for i, r in enumerate(ROWS) for j, c in enumerate(r) if G.raw_pipes(str(c))]
    print('  cells carrying an UNESCAPED pipe (checked BEFORE writing) : %d  %s' % (len(bad), 'PASS' if not bad else '### FAIL ### at %s' % bad))
    if bad:
        return 1
    slip = [m for m, s, _t, _p, _g, _sc, _st in ROWS if not s.startswith(m)]
    print('  marker is a literal prefix of its statement : %d/%d  %s' % (len(ROWS) - len(slip), len(ROWS), 'PASS' if not slip else '### FAIL ###'))
    if slip:
        return 1
    gen = [m for m, s, _t, _p, _g, _sc, _st in ROWS if not ('GENERAL' in s or 'PER CELL' in s)]
    print('  every row carries GENERAL or PER CELL in its statement : %s' % ('PASS' if not gen else '### FAIL ### %s' % gen))
    if gen:
        return 1
    present = [m for m, _s, _t, _p, _g, _sc, _st in ROWS if m in txt]
    if present:
        print('  ### ROW(S) ALREADY PRESENT -- NOTHING WRITTEN: %d' % len(present))
        got = [int(m.group(1)) for m in re.finditer(r'^\| (\d+) \|', txt, re.M)]
        print('  table rows now : %d   blank cells : %d' % (len(got), C.blank_cells(txt)))
        print('=' * 100)
        return 0
    nums = [int(m.group(1)) for m in re.finditer(r'^\| (\d+) \|', txt, re.M)]
    start = max(nums) + 1
    print('  last existing row : %d' % max(nums))
    print('  rows to append    : %d  (numbers %d..%d)' % (len(ROWS), start, start + len(ROWS) - 1))
    blank = [(i, j) for i, r in enumerate(ROWS) for j, c in enumerate(r) if not str(c).strip()]
    print('  blank cells in the new rows : %d  %s' % (len(blank), 'PASS' if not blank else '### FAIL ###'))
    if blank:
        return 1
    over = [i for i, r in enumerate(ROWS) if 'SCOPE' not in r[5] or 'M-2' not in r[5]]
    print('  rows carrying their own scope refusal and M-2\'s row : %d/%d  %s' % (len(ROWS) - len(over), len(ROWS), 'PASS' if not over else '### FAIL ###'))
    if over:
        return 1
    # ### the table's six cells, as row 132 has them: number | statement | terminal | profile | grade (with its scope) | status.
    lines = ['| %d | %s | %s | %s | %s %s | %s |' % (start + k, stmt, term, prof, grade, scope, status)
             for k, (_m, stmt, term, prof, grade, scope, status) in enumerate(ROWS)]
    new = txt.rstrip('\n') + '\n' + '\n'.join(lines) + '\n'
    open(TABLE + '.tmp', 'wb').write(new.encode('utf-8'))
    os.replace(TABLE + '.tmp', TABLE)
    back = io.open(TABLE, encoding='utf-8').read()
    got = [int(m.group(1)) for m in re.finditer(r'^\| (\d+) \|', back, re.M)]
    tail = back.rstrip('\n').split('\n')[-len(ROWS):]
    cellcounts = [len(G.split_cells(ln)) for ln in tail]
    ok = (got[-len(ROWS):] == list(range(start, start + len(ROWS))) and all(m in back for m, _s, _t, _p, _g, _sc, _st in ROWS)
          and C.blank_cells(back) == 0 and all(c == 6 for c in cellcounts) and all(all(x.strip() for x in G.split_cells(ln)) for ln in tail))
    print('  READ BACK         : last %d row number(s) are %s' % (len(ROWS), got[-len(ROWS):]))
    print('  cells on disk in the appended rows : %s  (6 required each, none blank)' % cellcounts)
    print('  blank cells after (line-scoped)   : %d' % C.blank_cells(back))
    print('  table rows now    : %d  %s' % (len(got), 'PASS' if ok else '### FAIL ###'))
    print('  ### and that means THE CELLS SURVIVED. It does not mean they are true.')
    print('=' * 100)
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
