# -*- coding: utf-8 -*-
"""b329_filings.py -- ONE APPEND-ONLY BLOCK IN PLACE-papers, GENERATED FROM THE ACT'S OWN RECORDS.

### ### `FACES_LEDGER.md` -- an UPDATE block naming row F5 (the fixed-point silence), written through the
### writer's `append_block` (b327_faces_row.py): **PROVED-GENERAL for the scaling part and PROVED-AT-CELLS
### for the compact part**; the rows above are never rewritten. ### The counts are read from
### `b329_kernel_run.txt` and the theorem names from the module's own source, never typed from memory.
### ### Two paths, two run files, numbered on a repeat writing run (b328's lesson).
"""
import io
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import b327_faces_row as W  # noqa: E402
import b329_correspondence as R  # noqa: E402

D = os.path.join(ROOT, 'data')
PP = r'D:\MY-DOwnloads\PLACE-papers'

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

LINES = []


def rec(s=''):
    LINES.append(s)
    print(s)


def texts():
    k = R.read_kernel()
    thms = R.read_module()
    gen = ', '.join('`%s`' % n for n, s in thms if s == 'GENERAL' and n in R.C1 + R.C2)
    cell = ', '.join('`%s`' % n for n, s in thms if s == 'PER CELL' and n in R.C2 + R.C3)
    faces = [
        '', '<!-- b329 update -->', '',
        '## UPDATE — filed 2026-09-05 (b329): row F5, the fixed-point silence',
        '',
        '*Rows above are never rewritten; an update names the row it bears on. Written through the writer\'s `append_block`.*',
        '',
        '| row | what b329 compiled | the row\'s standing after this act |',
        '|:--|:--|:--|',
        '| **F5** (the fixed-point silence) | `Core/FiniteSideSeal.lean` (namespace `B329`), vanilla Lean, no imports, `theorem` never `lemma`, no `native_decide`, no `sorry`; the profile %d → %d prints, all zero-axiom, the banked profile a true byte prefix of the new one (%s), the baseline regenerated byte-identically first (%s). GENERAL, over every base p ≥ 2, level, power and index: %s. PER CELL, decided over the explicit list (2,1), (2,2), (3,1), (3,2), (5,1), (7,1), (2,3) and no other: %s. The exhaustiveness theorem `finite_side_silence` carries both, its hypotheses naming which is which; its docstring quotes b310\'s fixed-point sentence. The registered coprimality form of "unit" and the `Nat.Coprime` form of the shift\'s invertibility are NOT compiled (the library\'s lemmas carry `propext`, measured at relay `data/b329_axiom_probe.txt`); the general theorems are equations with witnesses. | **PROVED-GENERAL (the scaling part: `p^j − 1` invertible modulo every `p^m`, the fixed-point congruence forces the index into the ball, in either congruence); PROVED-AT-CELLS (the compact part: the compressed smear over the units vanishes at the seven banked cells, with the not-dead witness and b304\'s refusal decided beside it; the opposite polarity UNAVAILABLE by b304\'s derivation, stated in the header).** The identification of the signed count with the source\'s trace stays b310\'s derivation, uncompiled; the archimedean member is untouched. |'
        % (k['before'], k['after'], k['prefix'], k['baseline'], gen, cell),
        '',
        '*Nothing about totality, h2, or the roster. M-2 remains owed under b310\'s cap. Filed by b329 (relay `data/b329_the_finite_side_seal.txt`).*',
    ]
    return faces


def main():
    fails = []
    rec('=' * 100)
    rec('b329 -- THE FILING. ### THE LEDGER UPDATE FOR F5, THROUGH THE WRITER.')
    rec('=' * 100)
    faces = texts()
    ok_words = ('PROVED-GENERAL' in faces[9] and 'PROVED-AT-CELLS' in faces[9] and 'UNAVAILABLE' in faces[9])
    rec('  the block carries PROVED-GENERAL, PROVED-AT-CELLS and the UNAVAILABLE arm : %s' % ok_words)
    if not ok_words:
        return 1
    st, det = W.append_block('<!-- b329 update -->', faces)
    rec('  FACES_LEDGER.md   %-16s %s' % (st, det))
    if st not in ('WRITTEN', 'DUPLICATE'):
        fails.append('FACES_LEDGER')
    led = io.open(os.path.join(PP, 'FACES_LEDGER.md'), encoding='utf-8', errors='replace').read()
    rec('  the b329 block once on disk : %s ; F5 row above untouched : %s'
        % (led.count('<!-- b329 update -->') == 1, '| F5 | F5 -- the fixed-point silence' in led))
    st2 = subprocess.run(['git', '-C', PP, 'status', '--porcelain', 'outputs/DEPOSITED-v1.1.2'], capture_output=True, text=True).stdout.strip()
    rec('  git status over outputs/DEPOSITED-v1.1.2 : %r ; THE DEPOSIT IS BYTE-UNCHANGED : %s' % (st2, not st2))
    if st2:
        fails.append('DEPOSIT')
    rec('  ### FILING CHECKS FAILING : %d %s' % (len(fails), fails if fails else ''))
    rec('=' * 100)
    return 0 if not fails else 1


if __name__ == '__main__':
    code = main()
    wrote = any('WRITTEN' in x for x in LINES)
    base = 'b329_filings_run' if wrote else 'b329_filings_rerun'
    k, name = 1, base + '.txt'
    while os.path.exists(os.path.join(D, name)):
        k += 1
        name = '%s%d.txt' % (base, k)
    io.open(os.path.join(D, name), 'w', encoding='utf-8', newline='\n').write('\n'.join(LINES) + '\n')
    sys.exit(code)
