# -*- coding: utf-8 -*-
"""b335_correspondence.py -- ONE ROW: THE STANDING CLAUSES, FILED. NO TERMINAL, AND THE REASON.

### ### **THE NOTATION GUARD AND THE BLANK-CELL AUDIT ARE IMPORTED, NEVER COPIED.** ### The counts are read from
### `b335_standing_run.txt`, never typed. ### **THE HAZARD:** a row that reads as if a filing were a result.
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import b302_correspondence as C   # noqa: E402
import b303_correspondence as G   # noqa: E402

SIDE = r'D:\SIDE-global-section'
TABLE = os.path.join(SIDE, 'CORRESPONDENCE.md')
D = os.path.join(ROOT, 'data')

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

SCOPE_TAIL = ("**SCOPE: FILINGS ONLY -- A STANDING-CLAUSES FILE WITH MEASURED PROVENANCE, A SCANNER CHECK BY ORDER, A RULE OF THE EXECUTOR'S "
              "FORMAT.** Nothing about the mathematics; no grade; no claim about the quantifier, h2, totality or the roster. NO AGGREGATION IS "
              "STATED; M-2 REMAINS (SPECIFIED-NOT-STATED) under b310's cap. The seam's debt item 1 restated, still unpaid. The patent lane carried "
              "on the patent seat's report, UNCONFIRMED on this seat's record. h2 stands exactly where the deposit left it. NOTHING DEPOSITS.")


def rows():
    run = io.open(os.path.join(D, 'b335_standing_run.txt'), encoding='utf-8').read()
    m = re.search(r'clauses measured (\d+) ; STANDING \(>= (\d+) of (\d+)\) (\d+) ; FREQUENT, NOT STANDING (\d+)', run)
    measured, maj, n, standing, freq = m.groups()
    marker = "THE STANDING CLAUSES, FILED: THE FERRIES' COMMON SCOPE, EXECUTION AND CLOSING CLAUSES IN ONE VERSIONED FILE, THE SCAN CHECKING THE CITATION, THE STOP FORMAT RULED (b335, leg 0 of the sortie)"
    return [
        (marker,
         marker + ": `relay/tools/FERRY_STANDING.md` VERSION 1, generated by a committed tool from the %s banked ferries b320-b334 -- %s clauses "
         "measured, %s STANDING (carried by %s or more of %s), %s FREQUENT, NOT STANDING, each with its count and carriers, the wording b334's ferry's "
         "(the reference the sortie names), the struck-clause record referenced and not restated; the file binds nothing by itself, a ferry cites it "
         "as `FERRY_STANDING v1`. THE FERRY SCAN edited BY THE ORDER'S WORDS: a citation of any version other than the current one is a hit "
         "(STALE), exercised both ways on ferry-shaped texts, the sortie ferry scanning as before; the struck and stem arms and their fixtures "
         "untouched, the diff additions only. THE EXECUTOR'S RULES gain Rule 6, appended -- the STOP format: closing summary, pins, then a block "
         "headed DRAFT -- NAVIGATOR EDITS with a draft of the next ferry, which binds nothing."
         % (n, measured, standing, maj, n, freq),
         "**NO TERMINAL, AND THE REASON: A FILING ACT** -- nothing here is a statement about the mathematics; nothing is finite-decidable because "
         "nothing is decided.",
         "**NO PRINT.** No findings section; no ledger row; the papers repo moves by one appended rule in `protocols/EXECUTOR_RULES.md`.",
         "**NO GRADE.** The standing file restates clauses the ferries already carry and adds none; the draft binds nothing; the scanner scans nothing "
         "it did not.",
         SCOPE_TAIL, "current"),
    ]


def main():
    ROWS = rows()
    txt = io.open(TABLE, encoding='utf-8').read()
    pos, neg = C.blank_check_fixture()
    sa, sb, sc, sd = G.split_fixture()
    print('=' * 100)
    print("b335 -- THE STANDING CLAUSES, FILED. ### THE ROW.")
    print('=' * 100)
    print('  BLANK-CHECK FIXTURE (imported from b302): real blank=%s  quiet on full=%s  %s' % (pos, neg, 'PASS' if (pos and neg) else '### FAIL ###'))
    print('  SPLITTER FIXTURE (imported from b303): plain=%s escaped=%s content=%s raw=%s  %s' % (sa, sb, sc, sd, 'PASS' if (sa and sb and sc and sd) else '### FAIL ###'))
    if not (pos and neg and sa and sb and sc and sd):
        return 1
    print('  blank cells in the whole table (line-scoped) : %d' % C.blank_cells(txt))
    bad = [(i, j) for i, r in enumerate(ROWS) for j, c in enumerate(r) if G.raw_pipes(str(c))]
    print('  cells carrying an UNESCAPED pipe (checked BEFORE writing) : %d  %s' % (len(bad), 'PASS' if not bad else '### FAIL ### at %s' % bad))
    if bad:
        return 1
    slip = [m for m, s, _t, _p, _g, _sc, _st in ROWS if not s.startswith(m)]
    print('  marker is a literal prefix of its statement : %s' % ('PASS' if not slip else '### FAIL ###'))
    if slip:
        return 1
    g1 = 'NO TERMINAL, AND THE REASON' in ROWS[0][2] and 'A FILING ACT' in ROWS[0][2] and 'NO GRADE' in ROWS[0][4] and 'binds nothing' in ROWS[0][1]
    print('  the row says NO TERMINAL with its reason, a filing act, no grade, the draft binding nothing : %s' % g1)
    if not g1:
        return 1
    present = [m for m, _s, _t, _p, _g, _sc, _st in ROWS if m in txt]
    if present:
        print('  ### ROW ALREADY PRESENT -- NOTHING WRITTEN.')
        got = [int(m.group(1)) for m in re.finditer(r'^\| (\d+) \|', txt, re.M)]
        print('  table rows now : %d   blank cells : %d' % (len(got), C.blank_cells(txt)))
        print('=' * 100)
        return 0
    nums = [int(m.group(1)) for m in re.finditer(r'^\| (\d+) \|', txt, re.M)]
    start = max(nums) + 1
    print('  last existing row : %d ; row to append : %d' % (max(nums), start))
    over = [i for i, r in enumerate(ROWS) if 'SCOPE' not in r[5] or 'M-2' not in r[5]]
    if over:
        print('  ### FAIL -- a row lacks its scope refusal or M-2')
        return 1
    lines = ['| %d | %s | %s | %s | %s %s | %s |' % (start + k, stmt, term, prof, grade, scope, status)
             for k, (_m, stmt, term, prof, grade, scope, status) in enumerate(ROWS)]
    new = txt.rstrip(chr(10)) + chr(10) + chr(10).join(lines) + chr(10)
    open(TABLE + '.tmp', 'wb').write(new.encode('utf-8'))
    os.replace(TABLE + '.tmp', TABLE)
    back = io.open(TABLE, encoding='utf-8').read()
    got = [int(m.group(1)) for m in re.finditer(r'^\| (\d+) \|', back, re.M)]
    tail = back.rstrip(chr(10)).split(chr(10))[-1]
    cells = G.split_cells(tail)
    ok = (got[-1] == start and all(m in back for m, _s, _t, _p, _g, _sc, _st in ROWS) and C.blank_cells(back) == 0 and len(cells) == 6 and all(x.strip() for x in cells))
    print('  READ BACK         : last row number is %d ; cells on disk %d (6 required, none blank)' % (got[-1], len(cells)))
    print('  table rows now    : %d  %s' % (len(got), 'PASS' if ok else '### FAIL ###'))
    print('  ### and that means THE CELLS SURVIVED. It does not mean they are true.')
    print('=' * 100)
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
