# -*- coding: utf-8 -*-
"""b370_bank.py -- THE BANK, WRITTEN FROM THE ACT'S OWN JSONS. ### **NO FIGURE IS TYPED.**"""
import io
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import run_clock       # noqa: E402
import banned_terms    # noqa: E402

D = os.path.join(ROOT, 'data')
OUT = os.path.join(D, 'b370_the_fold.txt')
REG = os.path.join(D, 'b370_registration_2026-09-08.txt')

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')


def J(n):
    return json.load(io.open(os.path.join(D, n + '.json'), encoding='utf-8'))


E, S, FL, L, Q = J('b370_reads'), J('b370_span'), J('b370_fold'), J('b370_lore'), J('b370_desk')
regtxt = io.open(REG, encoding='utf-8').read()
SHA = re.search(r'sha256 of every byte ABOVE this block : (\w+)', regtxt).group(1)
NBY = re.search(r'bytes locked : (\d+)', regtxt).group(1)
LAT = re.search(r'locked at \(UTC\) : (\S+)', regtxt).group(1)
NCL = len(J('b370_satisfiable')['clauses'])

LN = []


def w(s=''):
    LN.append(s)


BAR, SUB = '=' * 100, '-' * 100

w(BAR)
w('b370 -- THE FOLD, b361 THROUGH b369. ### THE BANK.')
w('2026-09-08. ### CONCURRENCY: SOLO (research seat). ### FERRY_STANDING v2, by reference, citation '
  'CURRENT.')
w('### Registration `data/b370_registration_2026-09-08.txt`, ### **LOCKED**')
w('### `%s`, %s bytes, %d clauses JOINTLY' % (SHA, NBY, NCL))
w("### SATISFIABLE, and ### **LOCKED ONLY AFTER THE AUDIT'S OWN EXIT CODE CAME BACK `0`**, locked at "
  '(UTC)')
w('### %s. ### **LOCKED BEFORE ANY WRITE OF THIS ACT.** ### The clocks are in section (8).' % LAT)
w(BAR)
w('')

w(SUB)
w('### (1) THE ANSWER, FIRST.')
w(SUB)
w('### ### ### **THE FOLD IS FILED, AND THE SPAN WAS COUNTED BEFORE IT WAS WRITTEN.**')
w('### The counter reads the last fold section`s own filing line off `FINDINGS.md` and counts forward:')
w('### ### **THE SPAN STARTS AT `b%d` AND RUNS THROUGH `b%d` -- `%d` ACTS**, and the fold names exactly'
  % (S['span_starts_at'], S['this_act'], S['current_span']))
w('### that range. ### **HAD THEY DISAGREED THE FOLD WOULD NOT HAVE BEEN WRITTEN**, and the tool has')
w('### that branch and can take it.')
w('### ### **`F-NOGRADE` HELD: GRADE STRINGS NOT FOUND VERBATIM IN THEIR OWN ACT`S BANK : `%d`.**'
  % FL['grade_misses'])
w('### ### **AND THE FOLD IS PURELY ADDITIVE:** ### `FINDINGS.md` before is a true prefix of')
w('### `FINDINGS.md` after (`%s`) and of its committed blob (`%s`), read ### **BEFORE THE PUSH.**'
  % (FL['prefix_of_file'], FL['prefix_of_blob']))
w('### `%d` lines appended, `%d` bytes; ### **`%d` EXISTING SECTIONS EDITED, `%d` GRADES MOVED, `%d`'
  % (FL['lines_appended'], FL['grew'], FL['sections_edited'], FL['grades_moved'],
     FL['acts_reverdicted']))
w('### ### ACTS RE-VERDICTED.**')
w('### ### ### **AND STEP ZERO IS DONE, WHICH IS THE PART THAT WAS OWED AND NOT ORDERED TWICE BEFORE.**')
w('### The span counter ### **READS AND NO LONGER WRITES**, its act number is read from the record')
w('### rather than baked into the file, and a caller who wants a record gets one ### **UNDER ITS OWN')
w('### ### STEM.**')
w('')

w(SUB)
w('### (2) STEP ZERO -- THE TOOL THAT WROTE INTO ANOTHER ACT.')
w(SUB)
w('### ### **THE DEFECT WAS THIS: `tools/b363_span.py` WROTE A RUN FILE AND A JSON UNDER `b363`S OWN')
w('### ### STEM ON EVERY RUN, WHOEVER RAN IT.** ### `b368` ran it to COUNT and rewrote `b363`s run')
w('### pointer; `b369` did the same one act later. ### **BOTH REVERTED IT. ### NEITHER FIXED IT.**')
w('### ### **THE ORDER`S OWN SENTENCE, AND IT IS THE WHOLE JUSTIFICATION:** ### *a lesson filed in a')
w('### bank and not built into a tool is a lesson that will be learned again.*')
w('### ### **WHAT THE FIX IS:**')
w('###   (1) ### **THE DEFAULT PATH WRITES NOTHING AT ALL.** ### It prints and returns `0`.')
w('###   (2) ### **`--emit bNNN` WRITES UNDER THE CALLER`S OWN STEM**, never under this file`s.')
w('###   (3) ### **THE ACT NUMBER IS READ FROM THE RECORD** -- the highest act with a banked file --')
w('###       instead of being a constant every later caller inherited silently.')
w('### ### ### **AND THE FIXTURE PROVES IT IN BOTH POLARITIES, WHICH IS THE HALF THAT MATTERS:**')
w('###   ### **(a)** ### a default run leaves the foreign pointer ### **BYTE-IDENTICAL**, hashed before')
w('###       and after and compared -- not promised in a docstring.')
w('###   ### **(b)** ### an `--emit` run ### **DOES** ### write, under the caller`s stem. ### Without')
w('###       (b) the arm would pass on a tool that had simply stopped working: ### **AN ARM THAT CANNOT')
w('###       ### FAIL IS NOT AN ARM**, which is `b363`s own sentence, applied to `b363`s own tool.')
w('###   ### **(c)** ### and the emit run leaves the foreign pointer alone too.')
w('### ### **AND WHAT THE FIX DOES NOT DO, SAID RATHER THAN LEFT:** ### it does not recover the two run')
w('### files already written under `b363`s stem. ### They stay where they are, and they are ###')
w('### **ARTIFACTS OF A DEFECT, NOT OF `b363`.**')
w('### ### ### **AND ONE THING THE FIX EXPOSED IMMEDIATELY:** ### with the act number read from the')
w('### record, the default run counts through the ### **LATEST BANKED ACT, WHICH IS THIS ONE** -- so it')
w('### returns `10`, not `9`. ### **THE FOLDING ACT IS NOT IN ITS OWN FOLD**, and the span this act')
w('### folds was counted with `--act 369`. ### **A DEFAULT THAT READS THE RECORD READS THE ACT DOING')
w('### ### THE READING TOO**, and that is stated here rather than left for the next caller to trip on.')
w('')

w(SUB)
w('### (3) COMPONENT 1 -- THE FOLD.')
w(SUB)
w('### ### **`%d` ROWS, EACH WITH ITS GRADE, ITS OWNING ACT AND ITS SCOPE SENTENCE.**' % FL['acts'])
w('### ### **EVERY GRADE STRING WAS REQUIRED TO APPEAR VERBATIM IN THE BANK OF THE ACT IT IS')
w('### ### ATTRIBUTED TO**, under the shared normaliser, or the section would not have been written.')
w('### ### ### **AND THE ATTRIBUTION WAS THE HARD HALF, NOT THE PRESENCE.** ### The grade word')
w('### `SUPPORTED-BY-THE-SOURCE`S-APPLICATION` is ### **`b366`S RULING, NOT `b365`S FINDING.** ###')
w('### `b365`s own bank says `SUPPORTED AT ζ, WITH A STATED CONSTANT`, and that is what `b365`s row')
w('### carries. ### **PUTTING `b366`S WORD IN `b365`S ROW WOULD HAVE FIRED THE ARM, AND IT SHOULD')
w('### ### HAVE.**')
w('### ### **`%d` OBSTACLES, EACH LOCATED BY THE ANCHOR TOOL IN THE BANK OF THE ACT THAT ORIGINATED'
  % FL['obstacles'])
w('### ### IT** -- never in a later act`s summary of it (`b360`s rule).')
w('### ### **AND TWO FURTHER TABLES, AS THE ORDER ASKED:** ### `%d` CORRECTIONS the acts made to their'
  % FL['corrections'])
w('### own readings and to each other`s, and `%d` acts` DECLARED DEFECTS. ### **A CORRECTION IS NOT A'
  % FL['defects'])
w('### ### RE-VERDICT AND THE TABLE SAYS WHICH IS WHICH.**')
w('### ### **THE DEFECTS TABLE IS NOT A CONFESSION AND IT IS NOT A BOAST.** ### It is there because the')
w('### arc`s claimed product is a record checkable by a reader who trusts none of it, and ### **A RECORD')
w('### ### WHOSE DEFECTS ARE DECLARED ONLY WHEN CONVENIENT IS NOT THAT.**')
w('')

w(SUB)
w('### (4) COMPONENT 2 -- THE ARC AS ONE STATEMENT.')
w(SUB)
w('### ### ### **THIS SPAN PRODUCED NO NEW MATHEMATICS ABOUT THE CLAUSE.**')
w('### ### **IT PRODUCED TWO RESULTS ABOUT THE CLAUSE`S SHAPE:** ### the approximation register located')
w('### and closed, with its obstruction identified as a RATE (`b362`); and the Li localization`s')
w('### archimedean half supported at `ζ` with a stated constant (`b361`, `b365`), under the grade word')
w('### `b366` ruled for that kind of support.')
w('### ### ### **AND ITS MAIN PRODUCT WAS NEITHER: IT WAS MAKING THE RECORD CHECKABLE BY A READER WHO')
w('### ### ### TRUSTS NONE OF IT.**')
w('### ### **SEVEN OF THE NINE ACTS PRODUCED NO RESULT ABOUT THE OBJECT AT ALL.** ### They built the')
w('### needle helper and measured its reach against the banks rather than the draft that proposed it;')
w('### diagnosed a failing suite instead of repairing it to pass; swept every arm in the record for a')
w('### species one of them had just minted; and found, measured and repaired a front document that had')
w('### been exporting eighteen names its source does not declare.')
w('### ### **A FOLD THAT LET THOSE SEVEN READ AS PROGRESS ON THE CLAUSE WOULD BE THE EXACT DEFECT THIS')
w('### ### SPAN SPENT ITSELF FINDING ELSEWHERE**, and that sentence is in the filed section, not only')
w('### here.')
w('### ### **SCOPE:** ### this is a statement about what the span put on the board, not about what is')
w('### true of the object. ### **THE CLAUSE HAS NOT MOVED AND NO ACT IN THE SPAN CLAIMS OTHERWISE.**')
w('### The two shape results are left at the grades their own acts gave them and are ### **NOT PROMOTED')
w('### ### HERE.**')
w('')

w(SUB)
w('### (5) COMPONENT 3 -- THE LORE, WITH ITS MINTS.')
w(SUB)
w('### ### **MINTED : `%d`. ### MODULES NOW UNDER `modules/2026-09` : `%d`. ### LOCAL COMMIT `%s`,'
  % (L['minted'], L['modules_now'], L['techne_head']))
w('### ### `%s` AHEAD OF `origin/main`, ### NOT PUSHED.**' % L['commits_ahead_of_origin'])
for m in L['modules']:
    w('###     `%s` -- %d bytes' % (m['name'], m['bytes']))
w('### ### **(i) `ONE INCIDENT DOES NOT SHOW YOU A PARTITION`.** ### A single failure licenses a CLASS,')
w('### never its PARTS. ### **NO MECHANIZABLE HALF AT ALL, AND THE MODULE SAYS SO FIRST** -- a tool can')
w('### count the instances a claim rests on; it cannot tell you about the parts you have not met,')
w('### because those leave nothing to count.')
w('### ### **(ii) `A PREDICATE THAT KNOWS ONE SHAPE FINDS ONE SHAPE`.** ### Five incidents in nine')
w('### acts. ### **THE SHARP ONE WAS CAUGHT BY RE-DERIVATION AND NOT BY ANY ARM**, and the reason is')
w('### structural: ### **THE GATE WOULD HAVE BEEN WRITTEN BY THE SAME HAND, IN THE SAME SITTING, WITH')
w('### ### THE SAME PREDICATE.** ### Mechanizable: whether a matcher was exercised against more than')
w('### one shape. ### Not: whether the shapes you thought to test are the shapes that exist -- ### **A')
w('### ### PREDICATE CAN BE WIDENED BUT NEVER SHOWN COMPLETE.**')
w('### ### **(iii) `THE DURABILITY SPLIT`.** ### A repair to a TRACKED file travels with a clone; a')
w('### repair to an UNTRACKED one does not. ### **SO THE GUARDS THAT HAVE CAUGHT THE MOST ARE THE ONES')
w('### ### A FRESH CLONE STARTS WITHOUT** -- the pre-push hook has refused more bad pushes than any')
w('### other single check here, and it has the shortest lifetime of any of them.')
w('### ### **AND THE THIRD IS MECHANIZABLE IN PART, AND THE MODULE SAYS WHICH PART:** ### whether a')
w('### guard`s file is tracked is one command per path with no judgement in it, and a tool ### **CAN')
w('### ### AND SHOULD** ### produce a DURABLE / NOT DURABLE column. ### **NO TOOL CAN RANK GUARDS BY')
w('### ### HOW MUCH THEY HAVE CAUGHT**, because that is in the prose of the acts they stopped.')
w('')

w(SUB)
w('### (6) COMPONENT 4 -- THE DESK, AND WHAT IS STILL OWED.')
w(SUB)
w('### ### **ITEMS SWEPT `%d`; CONFIRMED-BY-FILE `%d`; UNCONFIRMED `%d`; ### CLOSED `%d`.**'
  % (Q['items'], Q['confirmed'], Q['unconfirmed'], Q['items_closed']))
w('### ### ### **AND THIS IS THE THIRD TIME THE SAME NUMBER HAS BEEN REPORTED WITH THE SAME CAVEAT.**')
w('### `b368` swept and marked it; `b369` swept and said the result was weaker than it looks; `b370`')
w('### sweeps and gets the same answer again. ### **A MEASUREMENT WHOSE RESULT AND WHOSE CAVEAT BOTH')
w('### ### NEVER MOVE IS A MEASUREMENT NOBODY IS USING**, and three acts have now paid for it. ###')
w('### `b369`s draft asked the next act to re-verify ONE item properly; this order did not carry that,')
w('### ### **SO IT IS CARRIED FORWARD AGAIN -- WHICH IS ITSELF THE FINDING.**')
w('### ### **TWO ITEMS ARE NAMED AS STILL OWED, AND NEITHER IS CLOSED:**')
w('### ### **(i) THE COUNT CLAIM ABOVE THE REPAIRED LIST.** ### `b369` repaired the export list and')
w('### left the paragraph above it asserting a count of framework consequences. ### **THE FRONT')
w('### ### DOCUMENT IS NOT NOW CORRECT**, and no act has claimed it is.')
w('### ### **(ii) THE HOOK IS NOT DURABLE, AND A DURABLE FIX IS PRICED AND NOT BUILT.** ### The guard')
w('### already ships as a tracked file; what is missing is that ### **NOTHING FAILS WHEN IT IS NOT')
w('### ### INSTALLED.** ### The fix is a bootstrap step plus ### **AN ALREADY-DURABLE CHECK THAT FAILS')
w('### ### ON ITS ABSENCE** -- an arm in the closing suite reading `.git/hooks/pre-push` in every')
w('### rostered repository. ### **THE PRICE IS ONE ARM IN ONE SUITE PLUS A LINE IN THE PUSH')
w('### ### PROCEDURE.**')
w('### ### ### **AND THE ACT DOES NOT BUILD IT, WHICH IS WORTH NOTICING:** ### it is exactly the shape')
w('### of the STEP ZERO repair this act WAS sent to make -- ### **A LESSON FILED AND NOT BUILT.** ###')
w('### The order priced it and did not order it, and this seat does not widen its own order. ### **BUT')
w('### ### THE RECORD NOW HAS THE SAME SPECIES OPEN AGAIN, ONE COMPONENT AWAY FROM THE PLACE IT WAS')
w('### ### JUST CLOSED.**')
w('')

w(SUB)
w('### (7) COMPONENT 5 -- THE NEXT ARC, NAMED AND PRICED AND NOT OPENED.')
w(SUB)
w('### ### **THE FEDERATION CURRENCY AUDIT, IN THE SHAPE `b369` PRICED**, with the order`s two')
w('### corrections to that plan recorded here:')
w('### ### **CORRECTION ONE: IT ENUMERATES SURFACE KINDS, NOT REPOSITORIES ALONE.** ### `b369`s')
w('### ranking was built on repository DESCRIPTIONS and ### **THE DEFECT THE RECORD HAD JUST REPAIRED')
w('### ### DID NOT LIVE THERE** -- it lived in a front document. ### A ranking is only as wide as the')
w('### surface it reads, so the audit`s unit is the ### **SURFACE KIND** ### (description, `README`,')
w('### front document, module docstring) and each kind is swept across the federation rather than each')
w('### repository being swept across its kinds.')
w('### ### **CORRECTION TWO: ITS FIRST TARGET IS THE ONE CONFIRMED LIVE CLAIM.** ### `b369` located')
w('### exactly one: the construction kernel`s public description names a ### **Core terminal count**,')
w('### against a certified profile that is larger. ### **THE TWO NUMBERS ARE BOTH REAL AND THE')
w('### ### QUESTION IS WHETHER THE SMALLER IS A SCOPE OR A STALE FIGURE** -- and that is settled by ###')
w('### **ONE READ** ### of the kernel`s own printed profile against its own description.')
w('### ### **THE OUTCOME IS ONE OF TWO WORDS AND BOTH ARE ANSWERS:** ### `SCOPE-DEPENDENT` (the')
w('### description is counting a named subset and says so, or can be made to) or `STALE` (it is')
w('### counting what the kernel used to have).')
w('### ### ### **AND IT IS NOT OPENED HERE.** ### The profile is not read, no surface is read for')
w('### correctness, no repository is audited and no repository is graded. ### **THE READ THAT WOULD')
w('### ### SETTLE THE FIRST TARGET IS PRECISELY THE READ THIS ACT MAY NOT MAKE**, and naming it')
w('### precisely is what makes the next act cheap.')
w('')

w(SUB)
w("### (8) THE RECORD, ITS REFS, AND ITS CLOCKS.")
w(SUB)
w('###   `data/b370_registration_2026-09-08.txt` -- `%s`, %s bytes, locked %s.' % (SHA, NBY, LAT))
w('###   `data/b370_ferry_2026-09-08.txt` -- the order, banked verbatim.')
w('###   `data/%s` (%s) -- the extract-to-disk pass.' % (E['run_file'], E['run_clock']))
w('###   `data/%s` (%s) -- the span, counted.' % (S['run_file'], S['run_clock']))
w('###   `data/%s` (%s) -- the fold.' % (FL['run_file'], FL['run_clock']))
w('###   `data/%s` (%s) -- the mints.' % (L['run_file'], L['run_clock']))
w('###   `data/%s` (%s) -- the desk sweep.' % (Q['run_file'], Q['run_clock']))
w('###   `tools/b370_extract.py`, `tools/b370_regspec.py`, `tools/b370_reg_gate.py`,')
w('###     `tools/b370_fold.py`, `tools/b370_lore.py`, `tools/b370_desk.py`, `tools/b370_bank.py`.')
w('###   `tools/b363_span.py` -- ### **REPAIRED BY THIS ACT**, and the only owner instrument it touched.')
w('### ### **THE REF WRITTEN:** ### `PLACE-papers` at `%s` = `%s`.' % (E['papers_ref'], E['papers_head']))
w('')

w(SUB)
w("### (9) THE ACT'S OWN INCIDENTS, ALL DECLARED.")
w(SUB)
w('### ### **(i) `U-1`S COUNTER FIRED ON THIS REGISTRATION, AND THEN ON THE SENTENCE EXPLAINING IT.**')
w('### The face carried a spelled numeral governing the word the order uses for its own parts -- a')
w('### statement of fact about the ORDER`s shape, read as a prediction of this act`s artifacts. ### The')
w('### record banked that false positive at `b317`, `b318` and `b319` and its ruling is ### **REPHRASE,')
w('### ### DO NOT FIGHT THE COUNTER.** ### It was rephrased. ### **AND THEN THE EXPLANATION QUOTED THE')
w('### ### PHRASE AND FIRED IT AGAIN** -- the use-and-mention species (`b348`) meeting a lexical')
w('### scanner. ### The example is ELIDED and the elision is MARKED, which is `b367`s cure.')
w('### ### **(ii) THREE EXTRACT HINTS WERE TYPED ACROSS LINE WRAPS** and missed on the first run. ###')
w('### The tool refused them; they were retyped until it found the line. ### **THE LINE THE TOOL')
w('### ### RETURNS IS WHAT IS QUOTED, NEVER THE HINT.**')
w('### ### **(iii) THE REPAIRED SPAN COUNTER`S DEFAULT COUNTS THE ACT DOING THE READING.** ### Reading')
w('### the act number from the record means the default includes this act, so it returns `10` for a span')
w('### the fold names as `9`. ### **THE FOLDING ACT IS NOT IN ITS OWN FOLD.** ### Declared, and the')
w('### span was counted with an explicit `--act 369`.')
w('### ### **(iv) THE PLACEHOLDER-SPLIT SPECIES, AGAIN, IN THIS ACT`S OWN BANK WRITER.** ### A format')
w('### string ended one line and its argument was attached to the NEXT call, so the first line kept its')
w('### placeholder and the second raised. ### This is `b365`s species and the record has now met it in')
w('### `b365`, `b368`, `b369` and here. ### **IT IS CAUGHT EVERY TIME BY RUNNING THE WRITER AND NEVER')
w('### ### BY READING IT**, which is the only reason it stays cheap -- ### **AND IT IS THE SAME SHAPE AS')
w('### ### EVERYTHING ELSE THIS FOLD RECORDS: A LESSON FILED FOUR TIMES AND NOT BUILT INTO ANYTHING.**')
w('')

w(SUB)
w("### (10) THE EXPECTATIONS, SCORED. ### **AN EXPECTATION IS SCORED, NEVER SATISFIED.**")
w(SUB)
w('### ### **(E1) `THE COUNTED SPAN WILL AGREE WITH THE ORDER`S nine` -- MET.** ### The counter reads')
w('### `b%d` through `b%d`, `%d` acts, from the last fold`s own filing line.'
  % (S['span_starts_at'], S['this_act'], S['current_span']))
w('### ### ### **(E2) `THE NO-GRADE-MOVED ARM WILL FIRE AT LEAST ONCE BEFORE IT PASSES` -- REFUTED,')
w('### ### ### AND THE REASON IS MORE INTERESTING THAN A PASS.** ### The arm reported `%d` misses on'
  % FL['grade_misses'])
w('### its first and only run. ### **IT DID NOT FIRE BECAUSE THE CHECK IT MECHANIZES WAS RUN BY HAND')
w('### ### ONE STEP EARLIER:** ### this seat searched `b365`s bank for the grade word before writing')
w('### `b365`s row, found it absent, and located it at `b366` instead. ### **THE DISCIPLINE CAUGHT WHAT')
w('### ### THE ARM WAS BUILT TO CATCH, AND SO THE ARM HAD NOTHING TO CATCH.**')
w('### ### **THAT IS NOT THE ARM BEING USELESS AND THIS ACT DOES NOT CLAIM IT IS.** ### An arm that')
w('### never fires is either a discipline working or a check that cannot see; ### **THIS ONE CAN SEE --')
w('### ### IT WAS RUN AGAINST NINE STRINGS AND WOULD HAVE FIRED ON THE WRONG ATTRIBUTION** -- and the')
w('### only evidence of that is that the seat checked first. ### **A SEAT SAYING ITS OWN ARM WOULD HAVE')
w('### ### CAUGHT SOMETHING IT NEVER SAW IS EXACTLY THE CLAIM THIS RECORD DISTRUSTS**, so it is')
w('### recorded as what it is: the prediction was wrong, and the seat cannot prove why.')
w('### ### **BOTH EXPECTATIONS WERE PROCEDURAL AND NEITHER WAS ABOUT THE RECORD.** ### **A SEAT THAT')
w('### ### PREDICTS ONLY ITS OWN PROCEDURE HAS PREDICTED THE EASY HALF**, and this act predicted its')
w('### own error rate and got that wrong too.')
w('')

w(SUB)
w('### (11) WHAT IS NOT CLAIMED.')
w(SUB)
w('### ### **NO GRADE IS MOVED. ### NO ACT IS RE-VERDICTED. ### NOTHING IN THE FOLD IS NEW')
w('### ### MATHEMATICS. ### NO COORDINATE IS CLOSED. ### NO CLAUSE IS ADVANCED.**')
w('### ### **NO EXISTING SECTION OF `FINDINGS.md` IS EDITED** and no ledger row is moved.')
w('### ### **NO REPOSITORY IS AUDITED AND NO PUBLIC SURFACE IS READ FOR CORRECTNESS.** ### Component 5')
w('### is NAMED and PRICED; ### **THE PROFILE THAT WOULD SETTLE ITS FIRST TARGET IS NOT OPENED.**')
w('### ### **NO DESK ITEM IS CLOSED. ### NO DURABLE HOOK FIX IS BUILT. ### NO `.lean` FILE IS TOUCHED.')
w('### ### NO BUILD IS RUN. ### NO TECHNE MODULE IS PUSHED.**')
w('### ### **NO GRADE IS CONFERRED BY A SEAT AND NO FACE IS PROMOTED.**')
w('### ### **NOTHING IS CLAIMED ABOUT THE MATHEMATICS OF ANY NAMED SUBJECT.**')
w('### ### **NOTHING IS COMPUTED ABOUT THE OBJECT. ### NOTHING IS COMPILED AND NO BRIDGE IS TYPED.**')
w('### ### **THE PARTITION STAYS UNDECIDED. ### THE CLAUSE HAS NOT MOVED.**')
w("### ### **NOTHING HERE BEARS ON `h2`, ON TOTALITY OR ON THE ROSTER.** ### `M-2` remains")
w('### (SPECIFIED-NOT-STATED) under `b310`s cap. ### The seam`s debt item 1 stands. ### The patent lane')
w("### is carried on the patent seat`s report, UNCONFIRMED on this seat`s record. ### **THE POSTURE LOCK")
w('### ### IS SEPARATE.** ### **THE INSTRUMENT LANE STAYS PARKED. ### THE WAVE STAYS PARKED.** ### `h2`')
w('### stands exactly where the deposit left it. ### **NOTHING DEPOSITS.**')
w(BAR)


def main():
    body = chr(10).join(LN) + chr(10)
    io.open(OUT, 'w', encoding='utf-8', newline=chr(10)).write(body)
    back = io.open(OUT, encoding='utf-8').read()
    print(BAR)
    print('b370 -- THE BANK, WRITTEN FROM THE JSONS.')
    print(BAR)
    print('  written : %s ; %d lines ; %d bytes'
          % (os.path.basename(OUT), len(back.split(chr(10))), len(back.encode('utf-8'))))
    ph = re.findall(r'%[sd]', back)
    print('  ### ### **UNFORMATTED PLACEHOLDERS LEFT IN THE BANK : %d** %s' % (len(ph), ph[:4]))
    r = subprocess.run([sys.executable, os.path.join(ROOT, 'tools', 'banned_terms.py'),
                        '--new', OUT], capture_output=True, text=True, encoding='utf-8',
                       errors='replace')
    v = [x.strip() for x in (r.stdout or '').splitlines() if 'VERDICT' in x]
    print('  ### the banned-term review on this new file : %s' % (v[0] if v else '?'))
    print('  ### stems scanned : %s' % banned_terms.STEMS)
    ok = (not ph) and v and 'CLEAN' in v[0]
    print('  %s' % ('PASS' if ok else '### FAIL ###'))
    print(BAR)
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
