# -*- coding: utf-8 -*-
"""b414_components.py -- THE FIVE COMPONENTS AND THE ADDITION, RUN OVER THE ACT'S OWN ARTEFACTS.

### ### **EVERY QUOTE IS LIVE.** ### A component that quotes a file quotes the bytes on disk at run
### time; a needle that misses is COUNTED and printed, never silently dropped.
### ### **AND THIS ACT BUILDS**, so the components read the kernel's own stdout -- the build log and
### the regenerated axiom profile -- and never the act's word for what the build did.
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

D = os.path.join(ROOT, 'data')
KERN = os.path.join('D:', os.sep, 'SIDE-global-section')
CORE = os.path.join(KERN, 'Core')
NEW = os.path.join(CORE, 'SinglePrimeFactor.lean')
SEAL = os.path.join(CORE, 'FiniteSideSeal.lean')
PRINTS = os.path.join(KERN, 'AXIOM_PRINTS.txt')
BUILD = os.path.join(D, 'b414_build.txt')
LADDER = os.path.join(D, 'b414_ladder.txt')
EXTRACT = os.path.join(D, 'b414_extract.txt')
B413PRICE = os.path.join(D, 'b413_price.txt')
OUT = os.path.join(D, 'b414_components.txt')
SORTOUT = os.path.join(D, 'b414_sorted.txt')
NL = chr(10)

L = []
QFAIL = []


def say(s=''):
    L.append(s)


def rule(c='-'):
    say(c * 100)


def read(p):
    try:
        with open(p, 'rb') as fh:
            return fh.read().decode('utf-8', 'replace')
    except Exception as exc:
        QFAIL.append('%s : %s' % (os.path.basename(p), exc))
        return ''


def q(label, path, needle):
    """### **A LIVE QUOTE.** ### The needle is sought in the bytes on disk NOW, and a miss is a
    ### COUNTED FAILURE -- not a line the report quietly omits."""
    src = read(path)
    if needle in src:
        return True
    QFAIL.append('%s -- %r not in %s' % (label, needle[:56], os.path.basename(path)))
    say('      ### **LIVE-QUOTE MISS** -- %s' % label)
    return False


def wrap(text, width):
    """### **WRAP AT WORD BOUNDARIES.** ### `b410` paid for this once: a fixed-width slice split
    ### `that` into `t hat`, and a live-quote arm then measured the WRAPPER instead of the text.
    ### This act committed it again on the seal's own caveat, splitting `residue` into `a re` /
    ### `sidue`. ### **A REPORT THAT BREAKS ITS SUBJECT'S WORDS IS NOT QUOTING ITS SUBJECT.**
    """
    out, line = [], ''
    for w in (text or '').split(' '):
        if line and len(line) + 1 + len(w) > width:
            out.append(line)
            line = w
        else:
            line = (line + ' ' + w) if line else w
    if line:
        out.append(line)
    return out


def code_of(src):
    """### **STRIP COMMENTS AND DOCSTRINGS BEFORE SCANNING SOURCE** (`b410`'s `G-NOBORROWEDBAR`
    ### fired on its own explanation). ### Lean block comments are `/- ... -/`, lines are `--`."""
    s = re.sub(r'/-.*?-/', ' ', src, flags=re.S)
    return re.sub(r'(?m)--.*$', ' ', s)


# =============================================================================================
# ### **THE BUILD PHASE.** ### Folded into this tool rather than written as a SEVENTH act-tool,
# ### because the locked face's write list names ### **SIX** ### and a file of a KIND the write
# ### list does not name is a breach. ### It belongs here on the merits too: appending the
# ### prints, running the kernel and reading the profile back IS Component 3's substance.
# ###
# ### ### **`b329`'S CONVENTION, READ OFF ITS OWN LEDGER ROW AND NOT INVENTED HERE:** ### *the
# ### profile 566 -> 590 prints, all zero-axiom, the banked profile a TRUE BYTE PREFIX of the new
# ### one, the baseline regenerated byte-identically.* ### The import goes after the LAST import
# ### and the prints at the VERY END, because Lean emits in file order -- ### **AN INSERT
# ### ### ANYWHERE ELSE WOULD REORDER THE PROFILE AND THE PREFIX WOULD FAIL**, which is exactly
# ### why it is CHECKED rather than assumed.
# =============================================================================================
def run_build():
    import subprocess
    ALLP = os.path.join(KERN, 'AllPrints.lean')
    MODULE = 'SinglePrimeFactor'
    PFXOUT = os.path.join(D, 'b414_prints_prefix.txt')
    BL = []

    def rec(s=''):
        BL.append(s)
        print(s, flush=True)

    def rb(p):
        with open(p, 'rb') as fh:
            return fh.read()

    def wb(p, data):
        open(p + '.tmp', 'wb').write(data)
        os.replace(p + '.tmp', p)

    rec('=' * 100)
    rec('b414 BUILD PHASE -- THE PROFILE REGENERATED, PRIOR ONE PROVED A TRUE BYTE PREFIX.')
    rec('=' * 100)
    before_bytes = rb(PRINTS)
    before_lines = before_bytes.decode('utf-8', 'replace').splitlines()
    rec('  prior profile : %d bytes, %d lines' % (len(before_bytes), len(before_lines)))
    src = read(NEW)
    terms = re.findall(r'(?m)^theorem\s+(\w+)', code_of(src))
    rec('  terminals to print : %d' % len(terms))
    allp = io.open(ALLP, encoding='utf-8').read()
    lines = allp.splitlines()
    if ('import %s' % MODULE) in allp:
        rec('  import already present; not re-added.')
    else:
        li = max(i for i, ln in enumerate(lines) if ln.startswith('import '))
        lines.insert(li + 1, 'import %s' % MODULE)
        rec('  import inserted after line %d (the last import); 0 lines deleted' % (li + 1))
    added = 0
    for t in terms:
        stmt = '#print axioms %s.%s' % (MODULE, t)
        if stmt not in allp:
            lines.append(stmt)
            added += 1
    rec('  `#print axioms` lines appended at the END : %d' % added)
    wb(ALLP, (NL.join(lines) + NL).encode('utf-8'))
    rec('')
    rec('  running `lean AllPrints.lean` -- ### **AXIOM_PRINTS.txt IS ITS STDOUT.**')
    env = dict(os.environ, LEAN_PATH='build')
    r = subprocess.run(['lean', 'AllPrints.lean'], cwd=KERN, env=env,
                       capture_output=True, text=True, encoding='utf-8', errors='replace')
    rec('  exit code : %d' % r.returncode)
    if r.stderr.strip():
        rec('  ### STDERR (first 800 chars):')
        rec('      %s' % r.stderr[:800].replace(NL, NL + '      '))
    io.open(BUILD, 'w', encoding='utf-8', newline=NL).write(
        'exit=%d%sstdout bytes=%d%sstderr:%s%s%s'
        % (r.returncode, NL, len(r.stdout), NL, NL, r.stderr[:4000], NL))
    if r.returncode != 0:
        rec('  ### ### **BUILD DID NOT EXIT 0 -- REFUSING TO OVERWRITE THE PROFILE.**')
        io.open(PFXOUT, 'w', encoding='utf-8', newline=NL).write(NL.join(BL) + NL)
        return 2
    new_bytes = r.stdout.replace(chr(13) + NL, NL).encode('utf-8')
    after_lines = new_bytes.decode('utf-8').splitlines()
    rec('  new profile   : %d bytes, %d lines' % (len(new_bytes), len(after_lines)))
    prefix_ok = new_bytes.startswith(before_bytes)
    rec('')
    rec('  ### CLAUSE 1 -- ### **TRUE BYTE PREFIX : %s**' % ('YES' if prefix_ok else 'NO'))
    if not prefix_ok:
        n = min(len(before_bytes), len(new_bytes))
        i = next((k for k in range(n) if before_bytes[k] != new_bytes[k]), n)
        rec('      first differing byte at offset %d' % i)
        rec('      prior : %r' % before_bytes[max(0, i - 60):i + 60])
        rec('      new   : %r' % new_bytes[max(0, i - 60):i + 60])
    gained = len(after_lines) - len(before_lines)
    count_ok = (gained == len(terms))
    rec('  ### CLAUSE 2 -- lines gained %d, terminals added %d : ### **%s**'
        % (gained, len(terms), 'EQUAL' if count_ok else 'NOT EQUAL'))
    axiom_lines = [ln for ln in after_lines if 'depends on axioms' in ln]
    rec('  ### CLAUSE 3 -- lines reporting a NON-EMPTY profile : ### **%d**' % len(axiom_lines))
    for ln in axiom_lines[:10]:
        rec('      %s' % ln)
    rec('')
    for t in terms:
        hit = [ln for ln in after_lines if ("'%s.%s'" % (MODULE, t)) in ln]
        rec('  %-44s %s' % (t, hit[0] if hit else '### **NOT PRINTED**'))
    ok = prefix_ok and count_ok and not axiom_lines and all(
        any(("'%s.%s'" % (MODULE, t)) in ln for ln in after_lines) for t in terms)
    rec('')
    rec('  ### ### **VERDICT : %s**' % ('CLEAN ON ALL THREE CLAUSES' if ok else 'REFUSED'))
    if ok:
        wb(PRINTS, new_bytes)
        rec('  profile written : AXIOM_PRINTS.txt')
    else:
        rec('  ### ### **PROFILE NOT OVERWRITTEN.**')
    rec('=' * 100)
    io.open(PFXOUT, 'w', encoding='utf-8', newline=NL).write(NL.join(BL) + NL)
    return 0 if ok else 1


if '--build' in sys.argv:
    sys.exit(run_build())

rule('=')
say('b414_components.py -- LEG 1. ### THE PREDICATE NAMED, AND THE GENERAL CLAUSE STATED.')
rule('=')
say()

newsrc = read(NEW)
newcode = code_of(newsrc)
build = read(BUILD)
prints = read(PRINTS)
extract = read(EXTRACT)

# =============================================================================================
rule()
say('### COMPONENT 1 -- THE MODULE RULED.')
rule()
say('### THE FERRY`S RULING, QUOTED: ### *if the predicate can be stated in the axiom-free')
say('### module without an import, state it there and say what primitive it adds; if it cannot,')
say('### rule the statement into the interfaces module and say what that costs.*')
say()
say('### **THE ANTECEDENT IS A QUESTION OF FACT AND WAS SETTLED BY A BUILD.**')
core_files = sorted(f for f in os.listdir(CORE) if f.endswith('.lean'))
mathlib_in_core = sum(1 for f in core_files
                      if re.search(r'(?m)^import\s+Mathlib', read(os.path.join(CORE, f))))
say('  `.lean` files in `Core/` after this act      : %d' % len(core_files))
say('  MATHLIB imports anywhere in `Core/`          : ### **%d**' % mathlib_in_core)
imports_new = re.findall(r'(?m)^import\s+(\S+)', newsrc)
say('  imports of the new module                    : %s' % (', '.join(imports_new) or '(none)'))
say('  ### ### **AND `FiniteSideSeal` IS A `Core/` MODULE, NOT AN IMPORT FROM OUTSIDE THE')
say('  ### ### AXIOM-FREE SET.** ### `Core/` is made of module-to-module imports; the ruling`s')
say('  ### ### *without an import* can only mean without one from outside.')
say()
say('### ### ### **VERDICT: THE PREDICATE IS STATED IN THE AXIOM-FREE MODULE.** ### It compiles')
say('### there, with no Mathlib, and its profile is read below rather than assumed.')
say('### ### **SO THE RULING`S FIRST LIMB FIRES AND THE SECOND DOES NOT.** ### The statement is')
say('### NOT ruled into `Interfaces/`, and the navigator`s `(N5)` is answered by a build.')
say()
say('### ### **AND WHAT PRIMITIVE IT ADDS, NAMED EXACTLY:**')
q('the primitive is named in the module', NEW, 'THE ONE PRIMITIVE THIS MODULE ADDS')
say('  ### ### **A PRIMALITY NOTION.** ### `isPrime`, by trial division, as a `Bool`.')
say('  ### `Core/` carried ### **NO PRIME NOTION IN ANY FORM** ### before this act: the survey')
say('  ### found `3` declarations whose NAME carries a prime stem and ### **NOT ONE OF THEM')
say('  ### ### DECIDES PRIMALITY** -- `prime_free_window` names a window, ')
say('  ### `bench_primes_are_not_in_the_top_family` names a family, and')
say('  ### `first_level_prime_has_a_level_the_range_does_not_reach` names a level.')
say('  ### ### **A NAME IS NOT A NOTION, AND THE SURVEY CHECKED RATHER THAN COUNTING NAMES.**')
say()
say('### ### **THE COST OF THE FIRST LIMB, STATED AND NOT HIDDEN.** ### `Core/` is the module')
say('### whose whole character is that it assumes nothing the library would charge `propext`')
say('### for. ### **ADDING A PRIMALITY NOTION ADDS A PRIMITIVE TO A MODULE DEFINED BY HAVING')
say('### ### NONE.** ### It costs nothing in axioms -- the profile below is empty -- but it is a')
say('### widening of the module`s vocabulary, and the author should see it named rather than')
say('### discover it. ### **THE RULING CHOSE; THIS SEAT EXECUTED AND PRICED.**')
say()

# =============================================================================================
rule()
say('### COMPONENT 2 -- THE GENERAL CLAUSE STATED, AND ITS PROOF LEFT OPEN.')
rule()
say('### **THE STATEMENT, AS THE MODULE STATES IT:**')
q('the open statement is in the module docstring', NEW, 'THE NAMED OPEN STATEMENT')
say('      For every base `p` with `singlePrimeFactor p = true` and every level `n`,')
say('          `ballQ p n * sumAN p n = sumAQ p n`.')
say()
say('### ### **AND IT IS NOT PROVED HERE.**')
n_sorry = len(re.findall(r'\bsorry\b', newcode))
n_sorry_core = 0
for f in core_files:
    n_sorry_core += len(re.findall(r'\bsorry\b', code_of(read(os.path.join(CORE, f)))))
say('  `sorry` in this module`s CODE (comments stripped) : ### **%d**' % n_sorry)
say('  `sorry` anywhere in `Core/` CODE                  : ### **%d**' % n_sorry_core)
props = re.findall(r'(?m)^def\s+(\w+).*:\s*Prop\s*:=', newcode)
say('  `Prop`-valued definitions in this module          : ### **%d**' % len(props))
say('  ### ### **NOT A SORRY AND NOT A `Prop`-VALUED DEFINITION DRESSED AS A RESULT.**')
say()
say('### ### **THE IDIOM WAS FOUND BY DESCRIPTION, NOT BY THIS SEAT`S NAME FOR IT.** ### The')
say('### survey searched `Core/` for an unproved general statement and found ### **`4` MODULES**')
say('### carrying one -- `KLSilence`, `PairingShadow`, `PlancherelShadow`, `CrossPlaceShadow` --')
say('### each rendering it as ### **PROSE IN THE DOCSTRING PLUS A CORRESPONDENCE ROW, NEVER A')
say('### ### SORRY.** ### `KLSilence` says so in those words. ### This act follows the')
say('### convention; it does not improve on it.')
say()
say('### ### **WHAT IS COMPILED IS THE HYPOTHESIS.** ### The open statement`s subject is a')
say('### decidable predicate rather than a phrase, so a later seat cannot argue about what was')
say('### meant. ### **AND THE SEVEN CELLS SURVIVE AS THE INSTANCES THEY ARE:**')
seal_now = read(SEAL)
say('  `FiniteSideSeal.lean` theorems restated or renamed : ### **0**')
say('  `compact_smear_vanishes_at_cells` still in the seal : %s'
    % ('yes' if 'compact_smear_vanishes_at_cells' in seal_now else '### **NO -- BREACH**'))
q('the module says it does not touch the seal', NEW, 'It does not touch `FiniteSideSeal.lean`')
say()

# =============================================================================================
rule()
say('### COMPONENT 3 -- THE CONTROL RE-RUN FROM THE KERNEL, NOT FROM A TRANSCRIPTION.')
rule()
new_terms = re.findall(r'(?m)^theorem\s+(\w+)', newcode)
say('  terminals this module declares : ### **%d**' % len(new_terms))
for t in new_terms:
    say('      %s' % t)
say()
say('### ### **EVERY ONE OF THEM, AT ITS PRINTED AXIOM PROFILE, FROM THE KERNEL`S OWN STDOUT.**')
printed = 0
nonempty = 0
missing = []
for t in new_terms:
    key = 'SinglePrimeFactor.%s' % t
    hit = [ln.strip() for ln in prints.splitlines() if key in ln]
    if not hit:
        missing.append(t)
        say('  %-42s ### **NOT PRINTED -- REFUSES THE BANK**' % t)
        continue
    printed += 1
    line = hit[0]
    # ### A2: READ THE VERDICT LINE, NOT THE WORD AS A SUBSTRING.
    if 'does not depend on any axioms' in line:
        say('  %-42s does not depend on any axioms' % t)
    else:
        nonempty += 1
        say('  %-42s ### **%s**' % (t, line))
say()
say('  ### ### **TERMINALS PRINTED : %d OF %d. ### NON-EMPTY PROFILES : %d.**'
    % (printed, len(new_terms), nonempty))
if nonempty or missing:
    say('  ### ### **ANY NON-EMPTY PROFILE REFUSES THE BANK.** ### (K) BAR 2.')
say()
say('### ### **AND THE TRAP THIS ACT MET BEFORE THE LOCK, WHICH IS WHY THE PROFILE IS READ AND')
say('### ### NOT THE EXIT CODE:** ### a `decide` that exceeds `maxRecDepth` or `maxHeartbeats`')
say('### ### **DOES NOT FAIL CLEANLY -- IT YIELDS A TERMINAL CARRYING `sorryAx`.** ### Measured')
say('### in the scratch probe: at the default recursion depth three of four terminals compiled')
say('### to `sorryAx` while the fourth was clean, and the only thing that distinguished them was')
say('### the profile. ### **A GREEN BUILD IS NOT EVIDENCE; THE PROFILE IS.**')
say()
say('### ### **THE YIELD, MEASURED.**')
ident_bases = set()
for m in re.finditer(r'\[([0-9, ]+)\]\.all \(fun p => compactSmearHolds', newcode):
    ident_bases |= set(int(x) for x in m.group(1).split(','))
for m in re.finditer(r'compactSmearHolds (\d+) 1', newcode):
    ident_bases.add(int(m.group(1)))
pred_bases = set()
for m in re.finditer(r'\[([0-9, ]+)\]\.all \(fun p => (?:singlePrimeFactor|isPrime)', newcode):
    pred_bases |= set(int(x) for x in m.group(1).split(','))
b413_fail = [6, 10, 12, 14, 15, 18, 20, 21, 22, 26]
b413_hold = [4, 8, 9, 16, 25, 27, 32, 49]
say('  bases at which THE KERNEL re-decides the identity : ### **%d** -- %s'
    % (len(ident_bases), ', '.join(str(x) for x in sorted(ident_bases))))
say('  bases at which THE KERNEL decides the PREDICATE   : ### **%d** -- %s'
    % (len(pred_bases), ', '.join(str(x) for x in sorted(pred_bases))))
say()
reached_f = [p for p in b413_fail if p in ident_bases]
reached_h = [p for p in b413_hold if p in ident_bases]
say('  of `b413`s TEN counterexamples, re-decided here   : ### **%d** -- %s'
    % (len(reached_f), ', '.join(str(x) for x in reached_f)))
say('  of `b413`s EIGHT holding prime powers, re-decided : ### **%d** -- %s'
    % (len(reached_h), ', '.join(str(x) for x in reached_h)))
say('  the remainder stay `b413`s measurement, cited to `data/b413_extract.txt`.')
say()
say('### ### **THE BOUNDARY, AND WHY IT IS WHERE IT IS.** ### `decide` here is kernel reduction')
say('### over `List.range (p^(2n))` twice nested, so the work at a base grows like ### **`p^(4n)`**.')
if os.path.exists(LADDER):
    say('### The ladder, measured base by base:')
    for ln in read(LADDER).splitlines():
        if ln.strip():
            say('      %s' % ln.strip())
say('### ### **AN AFFORDABILITY LIMIT IS A PROPERTY OF KERNEL REDUCTION, NOT A RESULT ABOUT THE')
say('### ### ARITHMETIC.** ### The kernel not deciding `26` says nothing whatever about `26`;')
say('### `b413` decided it in Python in milliseconds. ### The two are not run together here.')
say()
say('### ### **AND THE PREDICATE`S OWN VERDICT REACHES EVERY ONE OF `b413`S EIGHTEEN BASES**,')
say('### because deciding `singlePrimeFactor` is trial division and costs nothing. ### So the')
say('### kernel now certifies ### **THE CLASSIFICATION AT ALL EIGHTEEN** ### and ### **THE')
say('### ### IDENTITY AT THE SUBSET IT CAN AFFORD** -- two different reaches, kept apart.')
say()

# =============================================================================================
rule()
say('### COMPONENT 4 -- THE TWENTY-EIGHT, SORTED BY WHAT A PROOF WOULD REACH.')
rule()
rows = [ln for ln in read(B413PRICE).splitlines() if ln.strip() and chr(9) in ln]
say('  rows re-read from `b413`s own record : ### **%d**' % len(rows))
say()
say('### ### **THE SORT`S RULE, STATED BEFORE THE SORT IS RUN.** ### A sentence lands in')
say('### ### **GROUP A** ### if a proof of the open statement would make it true AS WRITTEN --')
say('### that is, if what it asserts is the vanishing itself, over an index the statement')
say('### reaches. ### It lands in ### **GROUP B** ### if a proof would leave it exactly as it')
say('### is, because what it asserts is about something else: compilation status, scope, the')
say('### archimedean place, an aggregation, or a plan.')
say()
say('### ### **AND THE FACT THAT DECIDES MOST OF THEM, WHICH THIS ACT DID NOT EXPECT:**')
say('### ### **THE CORPUS`S OBJECT INDEXES ITS FINITE PLACES BY PRIMES.** ### Every base the')
say('### corpus actually uses is prime, and ### **EVERY PRIME HAS A SINGLE PRIME FACTOR.** ###')
say('### So the open statement, if proved, covers ### **THE WHOLE RANGE THOSE SENTENCES EVER')
say('### ### INTENDED** -- and the failure at `6` was never a threat to any of them.')
say('### ### **WHAT WAS ALWAYS THE THREAT IS THAT THE STATEMENT WAS PROVED AT SEVEN CELLS.**')
say()
VANISH = ('silence', 'silent', 'annihilat', 'vanish', 'fixed-point', 'fixed point',
          'closure', 'compact part', 'smear')
ELSEWHERE = ('compiled', 'compil', 'archimedean', 'aggregation', 'M-2', 'profile',
             'Bank:', 'Registration gate', 'keyed', 'correspondence', 'desk', 'FOOT:',
             'paste begins', 'CLOSING', 'priced', 'cost')

# ### **THE HAND-READ, RECORDED ROW BY ROW WITH ITS REASON.** ### `A` = a proof of the open
# ### statement makes this true AS WRITTEN. ### `B` = a proof leaves it exactly as it is.
# ### ### **THE INDEX IS THE ROW'S POSITION IN `b413`'s OWN RECORD**, so the two passes are
# ### compared on the same objects and not on two different readings of the file.
HAND = {
    1:  ('B', 'a statement about what the MODEL carries, not about the vanishing'),
    2:  ('A', 'the first-level mass is annihilated -- unqualified vanishing claim'),
    3:  ('B', 'a work order naming objects and radii'),
    4:  ('A', "the finite side's closure reads as ONE statement -- unqualified"),
    5:  ('A', 'the finite side cannot supply the first-level mass -- unqualified'),
    6:  ('A', "the closure is one statement with one mechanism -- unqualified"),
    7:  ('B', 'a paste header and a work order'),
    8:  ('B', 'a SCOPE clause -- and the one sentence here that was already careful'),
    9:  ('B', 'a question about whether the mechanism reaches infinity, not a claim'),
    10: ('B', 'a fold work order'),
    11: ('A', 'the finite side is arithmetically silent by one mechanism -- unqualified'),
    12: ('B', 'a plan item naming what the corpus holds'),
    13: ('B', 'about a construction the finite side supplies, not about vanishing'),
    14: ('B', 'a closing work order'),
    15: ('B', 'a plan: the sealing module follows'),
    16: ('B', 'a closing work order'),
    17: ('B', 'a work order about the profile and the rows'),
    18: ('B', 'a work order line'),
    19: ('B', 'a filename'),
    20: ('A', "the silence is one compiled statement -- and its second clause, that the "
              "generality is honest in its own header, is what THIS ACT refuted"),
    21: ('B', 'about compilation status'),
    22: ('B', 'a desk list'),
    23: ('B', 'a fold work order'),
    24: ('A', 'the seal IS exhaustiveness over places -- unqualified characterisation'),
    25: ('A', "the finite side's zero as one of two found witnesses -- unqualified"),
    26: ('B', 'ALREADY QUALIFIED -- *at one place and one level*; a proof dates it, not falsifies'),
    27: ('B', "a heading about the qualifier itself"),
    28: ('B', 'an expectation about sentences, not a claim about the finite side'),
}

mA, mB = [], []
for n, r in enumerate(rows, 1):
    act, _, txt = r.partition(chr(9))
    low = txt.lower()
    hits_v = [w for w in VANISH if w in low]
    hits_e = [w for w in ELSEWHERE if w.lower() in low]
    (mA if (hits_v and not hits_e) else mB).append(n)
say('  ### **PASS 1 -- THE MECHANICAL SPLIT, AND ITS YIELD PRINTED IN FULL.**')
say('      keyword rule: a VANISHING word present and no ELSEWHERE word present -> A')
say('      GROUP A : %d -- rows %s' % (len(mA), ', '.join(str(x) for x in mA) or 'none'))
say('      GROUP B : %d -- rows %s' % (len(mB), ', '.join(str(x) for x in mB) or 'none'))
say()
say('  ### ### **AND THE MECHANICAL SPLIT IS DISCARDED, WITH ITS YIELD ON THE RECORD.**')
say('  ### Its ELSEWHERE list fires on a word anywhere in the sentence, including inside a')
say('  ### SCOPE CLAUSE -- so a sentence whose CLAIM is the vanishing lands in `B` because its')
say('  ### scope says *nothing about the archimedean place*. ### **THE MATCHER IS MEASURING')
say('  ### ### WHERE A WORD APPEARS, NOT WHAT THE SENTENCE ASSERTS.**')
say()
say('  ### **PASS 2 -- THE HAND-READ, ROW BY ROW, WITH A REASON ON EVERY ROW.**')
A, B = [], []
for n, r in enumerate(rows, 1):
    act, _, txt = r.partition(chr(9))
    g, why = HAND.get(n, ('B', 'unclassified'))
    (A if g == 'A' else B).append((n, act, txt, why))
say('  ### ### **GROUP A -- A PROOF WOULD MAKE THESE TRUE AS WRITTEN : %d**' % len(A))
for n, act, txt, why in A:
    say('      %2d  %-30s %s' % (n, act, why))
    say('              %s' % txt[:140])
say()
say('  ### ### **GROUP B -- A PROOF WOULD LEAVE THESE EXACTLY AS THEY ARE : %d**' % len(B))
for n, act, txt, why in B:
    say('      %2d  %-30s %s' % (n, act, why))
say()
handA = set(n for n, _a, _t, _w in A)
dis = sorted(set(mA) ^ handA)
say('  ### ### **THE TWO PASSES DISAGREE ON %d OF %d ROWS : %s**'
    % (len(dis), len(rows), ', '.join(str(x) for x in dis)))
say('  ### ### **THE HAND-READ GOVERNS, AND THE MATCHER`S YIELD IS PRINTED RATHER THAN')
say('  ### ### QUIETLY REPLACED** -- a limit found by a matcher is a property of the matcher')
say('  ### until a second shape has been tried, and here the second shape was a reader.')
say()
say('  ### ### **SENTENCES EDITED BY THIS ACT : `0`. ### IN EITHER GROUP.**')
say('  ### ### **SORTING IS NOT REPAIRING**, and a sentence made true by a statement nobody has')
say('  ### ### proved is ### **STILL NOT TRUE.** ### The groups are kept apart under `(R27)`')
say('  ### rather than averaged into one number.')
io.open(SORTOUT, 'w', encoding='utf-8', newline=NL).write(
    NL.join(['THE HAND-READ GOVERNS. THE MECHANICAL PASS IS PRINTED ABOVE IT IN THE COMPONENTS.',
             '', 'MECHANICAL GROUP A (%d) : %s' % (len(mA), mA),
             'MECHANICAL GROUP B (%d) : %s' % (len(mB), mB),
             'THE TWO PASSES DISAGREE ON %d OF %d ROWS : %s' % (len(dis), len(rows), dis), '',
             'GROUP A (%d)' % len(A)]
            + ['%d	%s	%s	%s' % (n, a, w, t) for n, a, t, w in A]
            + ['', 'GROUP B (%d)' % len(B)]
            + ['%d	%s	%s	%s' % (n, a, w, t) for n, a, t, w in B]) + NL)
say('  written : %s' % os.path.basename(SORTOUT))
say()

# =============================================================================================
rule()
say('### COMPONENT 5 -- THE PRICE RE-TAKEN NOW THAT THE STATEMENT EXISTS.')
rule()
say('### `b413` priced `(N)` at ### **AT LEAST TWO ACTS, UPPER END NOT GIVEN**, and named act 1')
say('### as *state it*. ### **THIS IS ACT 1, AND IT IS DONE.**')
say()
say('### ### **WHAT ACT 1 ACTUALLY COST, FROM THIS ACT AND NOT FROM AN ESTIMATE:**')
say('  new `.lean` modules                     : 1')
say('  new kernel terminals                    : %d' % len(new_terms))
say('  lines of the new module                 : %d' % len(newsrc.splitlines()))
say('  existing `.lean` files edited           : ### **0**')
say('  Mathlib imports added                   : ### **0**')
say('  axioms added                            : ### **0**')
say('  ### ### **SO THE FLOOR`S FIRST ACT WAS ONE ACT, AS PRICED.** ### `b413`s floor of two is')
say('  ### **NOT MOVED BY THIS ACT: IT IS HALF-DISCHARGED.** ### One remains, at minimum.')
say()
say('### ### **AND IS THE UPPER END ANY MORE NAMEABLE NOW? ### NO -- AND THE ACT CAN NOW SAY')
say('### ### WHY WITH A MEASUREMENT RATHER THAN A JUDGEMENT.**')
say('### The statement`s own evidence is a `decide` over a finite list. ### This act measured')
say('### what that costs: the work at a base grows like ### **`p^(4n)`**, and the kernel`s')
say('### reduction ran out before `b413`s Python did, at a base `b413` handled instantly.')
say('### ### **A PROOF CANNOT BE REACHED BY EXTENDING THE LIST** -- not because the list is')
say('### long but because ### **NO FINITE LIST IS THE STATEMENT.** ### The proof needs an')
say('### argument about `units p n` being the unit group, which is a change of ### **KIND**, and')
say('### naming its length still requires attempting it, ### **WHICH IS BUILDING.**')
say()
say('### ### ### **VERDICT ON THE PRICE: ### ONE ACT SPENT, AT LEAST ONE REMAINING, AND THE')
say('### ### ### UPPER END IS STILL NOT THIS SEAT`S TO GIVE.**')
say()

# =============================================================================================
rule()
say('### THE ADDITION -- THE NAVIGATOR`S OWN ERROR, ENTERED IN HIS WORDS.')
rule()
say('### ### **QUOTED FROM THE FERRY, NOT PARAPHRASED:**')
say('###     *"primality unused" was carried across twenty ferries as if it licensed')
say('###     generality, when it was true of the clauses that carry no value and false of')
say('###     the clause that does.*')
say()
say('### ### **IT IS ENTERED AND IT IS NOT ARGUED WITH.** ### The seat`s job is to record it')
say('### and to measure what can be measured about it.')
say()
say('### ### **AND THE SAME ERROR IS WRITTEN IN THE KERNEL ITSELF, IN ADVANCE.** ### `(T1.4)`,')
say('### quoted from `FiniteSideSeal.lean` at the survey:')
i = seal_now.find('(T1.4)')
j = seal_now.find('(T1.6)', i)
if i >= 0 and j > i:
    quoted = re.sub(r'\s+', ' ', seal_now[i:j]).strip()
    for seg in wrap(quoted, 94):
        say('###     %s' % seg)
else:
    QFAIL.append('the seal caveat (T1.4) is no longer readable')
say()
say('### ### **SO THE FILE SAID *primality is used nowhere in this file and the general theorems')
say('### ### hold for every `p >= 2`* -- WHICH IS TRUE OF (a) AND (b) AND SAYS NOTHING ABOUT')
say('### ### (c).** ### The navigator`s sentence and the file`s sentence are ### **THE SAME')
say('### ### SENTENCE**, and neither is false: each is true of the clauses that carry no value.')
say('### ### **THE ERROR IS NOT IN EITHER SENTENCE. ### IT IS IN CARRYING ONE ACROSS A CLAUSE')
say('### ### OF A DIFFERENT KIND** -- which is `(R28)` exactly, written before anyone knew this')
say('### act would need it.')
say()
say('### ### **AND THE FILE NAMED THE WRONG CONDITION FOR THE MISSING IDENTIFICATION.** ### It')
say('### says *exactly when `p` is prime*. ### Measured over bases `2` to `50` at level `1`:')
m = re.search(r'held by the identity but NOT prime\s*:\s*### \*\*(\d+)\*\*\s*--\s*(.+)', extract)
if m:
    say('###     bases the identity holds at that are NOT prime : ### **%s** -- %s'
        % (m.group(1), m.group(2).strip()))
else:
    QFAIL.append('the extract no longer carries the too-strong measurement')
say('###     decided cells the caveat would exclude          : ### **0**')
say('### ### **A CAVEAT SOUND ON ITS OWN EVIDENCE IS NOT A CAVEAT TESTED.** ### It was exactly')
say('### right on the seven cells and wrong on everything else, and it was carried from `b329`')
say('### to this act -- ### **85 ACTS** -- without a base outside its range ever being tried.')
say('### ### **NO `.lean` FILE`S EXISTING TEXT IS EDITED TO FIX IT.** ### The correction lives')
say('### in the new module and in the correspondence row, additively.')
say()

# =============================================================================================
rule()
say('### THE EXPECTATIONS, SCORED OVER NAMED POPULATIONS UNDER `(R26)`.')
rule()
say('**`(N5)`** ### over ### **the design decision between `Core/` and `Interfaces/`**')
say('      *the decision rules for `Interfaces/`, because a prime predicate in `Core/` is a new')
say('      primitive in a module defined by having none*')
say('      ### ### **REFUTED BY A BUILD.** ### The ruling`s antecedent is true: the predicate')
say('      compiles in `Core/` with no Mathlib and an empty axiom profile, so the ruling`s FIRST')
say('      limb fires and the statement stays in the axiom-free module. ### **AND THE')
say('      ### EXPECTATION`S REASON SURVIVES ITS REFUTATION** -- it IS a new primitive in a')
say('      module defined by having none, which is why the act names it rather than burying it.')
say('      ### **THE NAVIGATOR WAS RIGHT ABOUT THE COST AND WRONG ABOUT THE DECISION**, and the')
say('      decision was the author`s ruling, not this seat`s preference.')
say()
say('**`(N6)`** ### over ### **the Lean act as `b413` priced it**')
say('      *stating it correctly costs one act and the floor does not move*')
say('      ### ### **MET, BOTH LIMBS.** ### One act, and the floor of two stands with one act')
say('      spent against it.')
say()

rule()
say('### THE COMPONENTS` OWN TALLY.')
rule()
say('  ### ### **LIVE-QUOTE FAILURES : %d**' % len(QFAIL))
for f in QFAIL:
    say('      %s' % f)
rule('=')

io.open(OUT, 'w', encoding='utf-8', newline=NL).write(NL.join(L) + NL)
print(NL.join(L))
print()
print('wrote %s' % os.path.basename(OUT))
sys.exit(1 if QFAIL else 0)
