# -*- coding: utf-8 -*-
"""b420_desk_bank.py -- THE DESK, THE TRAIL, THE CORRESPONDENCE ROW, THE KEY AND THE BANK.

### ### **ROWS ARE READ BY MARKER, NEVER BY NUMBER.** ### Row 263 is annotated by THIS act's appended row,
### which names it by its marker; row 263's bytes are not touched. ### `(R36)`'s instrument item goes in the
### trail block with a trigger that can fire, so `(R23)` does not shelve it.
"""
import io
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import b302_correspondence as C   # noqa: E402
import b303_correspondence as GD  # noqa: E402

D = os.path.join(ROOT, 'data')
PP = os.path.join('D:', os.sep, 'MY-DOwnloads', 'PLACE-papers')
SIDE = os.path.join('D:', os.sep, 'SIDE-global-section')
TRAILS = os.path.join(PP, 'OPEN_TRAILS.md')
TABLE = os.path.join(SIDE, 'CORRESPONDENCE.md')
INDEX = os.path.join(ROOT, 'tools', 'banked_index.py')
MARK = '<!-- b420 the proof cited, the lock ruled, and the lemma aimed at the right object -->'
PRIOR = '<!-- b419 the helper fixed, the clause printed -->'
B419ROW = "**THE GENERAL CLAUSE IS PROVED, ZERO AXIOMS, ON THE FIRST PROBE**"
B414ROW = "**THE KERNEL'S OWN HEADER NAMED THE MISSING IDENTIFICATION IN ADVANCE AND NAMED THE WRONG CONDITION FOR IT"
BANKOUT = os.path.join(D, 'b420_the_lemma_aimed.txt')
NL = chr(10)

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

LINES = []


def rec(s=''):
    LINES.append(s)
    print(s, flush=True)


def bar(c='-'):
    rec(c * 100)


def read(p):
    try:
        with open(p, 'rb') as fh:
            return fh.read().decode('utf-8', 'replace')
    except Exception:
        return ''


def write_bytes(path, text):
    data = text.encode('utf-8')
    open(path + '.tmp', 'wb').write(data)
    os.replace(path + '.tmp', path)
    return len(data)


def wrap(text, width):
    out, line = [], ''
    for w in (text or '').split(' '):
        if line and len(line) + 1 + len(w) > width:
            out.append(line)
            line = w
        else:
            line = (line + ' ' + w) if line else w
    if line:
        out.append(line)
    return out


FACE = read(os.path.join(D, 'b420_registration_2026-09-11.txt'))
SEALHASH = re.search(r'([0-9a-f]{64})', FACE.split('THE REGISTRATION LOCK')[-1]).group(1)
LG = read(os.path.join(D, 'b420_lockgate_notes.txt'))
_g = re.search(r'GATES READ : (\d+)\. ### PASSING : (\d+)\. ### FACE-SUBJECT GATES CHECKED BY DIGEST : (\d+)', LG)
GR, GDG = (int(_g.group(1)), int(_g.group(3))) if _g else (0, 0)

FOUR = ('**LIST 1** — the rows that cite at a ref nobody can name (b373). **OPEN.** **LIST 2** — the rows grading '
        'a declaration the record has classified absent (b373). **OPEN.** **LIST 3** — the undated figures across the '
        'roster (b374). **OPEN.** **LIST 4** — the bibliography entries nothing cites (b374). **OPEN.** Trigger: the '
        'ruling on which test governs, or any disposition on the four open lists.')

DESK = [
    ('the four open lists', 'STANDING', 'All four OPEN; their trigger has not fired.'),
    ('W-ORD-LI-WEIL-BRIDGE', 'STANDING', 'The author’s word; not fired.'),
    ('W-ORD-DISCRIMINATING-FAMILY / W-ORD-LI-FAMILY-CONTROL', 'STANDING', 'Blocked by the PARKED instrument lane.'),
    ('the lock that refused on a ferry’s own word', 'CLOSE',
     'RULED BY THE AUTHOR, (R36), ROUTE (1): a scan hit is resolved by re-paste, one action per hit, no tool changed.'),
    ('the scan’s sites against the lock’s zero', 'STANDING',
     'AN INSTRUMENT ITEM, recorded in the trail with its trigger -- the author opens an instrument lane. Not opened.'),
    ('SinglePrimeFactor’s docstring, which called the statement open', 'CLOSE',
     'ANNOTATED BY INSERTION at both passages, striking nothing: it now cites SmearGeneral.smear_general. The profile '
     'regenerated byte-identical to the pin’s.'),
    ('correspondence row 263', 'CLOSE', 'ANNOTATED BY THIS ACT’S APPENDED ROW, which names it by its marker; its bytes unchanged.'),
    ('the eight sentences b419 qualified', 'CLOSE',
     'LISTED AND ANNOTATED IN THIS ACT’S RECORD, each beside the terminal; they live in banked ferries, never edited.'),
    ('the identification with the source’s trace', 'STANDING',
     'PRICED: part (i), on the finite ambient, one lemma after new definitions of the operator and its trace; part (ii), '
     'the source’s frame carried to that ambient, not statable in the kernel’s present character -- a Mathlib import '
     'is the floor of its price, not a quote.'),
    ('b419’s kernel-write clauses', 'CLOSE',
     'RE-READ: 8 clauses, 3 NOT MEETABLE AS WRITTEN -- b419 printed one; the same wording stood at (C)(ii)’s headline '
     'and KIND 4. Corrected forms banked for later faces; no standing clause added.'),
    ('the barrier lemma on positivity', 'CLOSE',
     'NOT AN INSTANCE, ON FORM: the arc’s positivity argument is row S1’s table of constituents at their owners’ '
     'grades -- measured, imported, derived on content, one compiled counting form, and the class quantifier K8 '
     'UNOWNED -- not a chain the lemma quantifies over. Aiming at the right-hand side removed b410’s obstacle; '
     'b407’s remains.'),
    ('the determined structure on the class’s test functions', 'STANDING',
     'NOT SUPPLIED BY THE RECORD: no document writes a specification for it; the keystone names only xi.'),
    ('the Reader’s encoding', 'STANDING', 'ROUTED, NOT REPAIRED, as at b416.'),
    ('§9’s certificate; the `I-7` collision; the ten arcs; the deposited title', 'STANDING', 'ROUTED, unchanged by this act.'),
    ('row U1', 'STANDING', 'FROZEN AT SIX; no entry written, the verdict not being INSTANCE.'),
    ('M-2', 'STANDING', 'OWED and stays owed.'),
    ('h2', 'STANDING', 'WHERE THE DEPOSIT LEFT IT.'),
]


def do_desk():
    for item, want, why in DESK:
        rec('    %-72s %s' % (item[:72], want))
        for seg in wrap(why[:1600], 150):
            rec('        %s' % seg)
    closed = [m for m in DESK if m[1] == 'CLOSE']
    rec('')
    rec('    ### ### **ITEMS SWEPT : %d. ### CLOSED : %d. ### STANDING : %d.**' % (len(DESK), len(closed), len(DESK) - len(closed)))
    return dict(items=len(DESK), closed=len(closed), standing=len(DESK) - len(closed))


def trail_block():
    return [
        '', MARK, '',
        '### b420 — the proof cited, the lock ruled, and the lemma aimed at the right object — filed 2026-09-11', '',
        '#### The lock and the scan', '',
        '**(R36), the author’s: route (1).** A ferry-scan hit is resolved by re-paste, one action per hit, and no tool '
        'changes.',
        '',
        '**INSTRUMENT ITEM (R36), NOT OPENED.** The scan’s own doctrine reads a hit as a site for a reader; the lock '
        'gate admits only a scan of zero. The mismatch stands as an item for the instrument lane. **Trigger: the author '
        'opens an instrument lane.**',
        '',
        '#### The proof cited', '',
        '`SinglePrimeFactor.lean` now cites `SmearGeneral.smear_general` beside both passages that called the statement '
        'open, every original word kept; the regenerated profile is byte-identical to the pin’s. Correspondence row 263 '
        'is annotated by this act’s appended row, not edited. The eight sentences b419 qualified live in banked ferries '
        'and are annotated in this act’s record.',
        '',
        '#### The reach, priced', '',
        'The step from the model’s count to the source’s trace is two parts in the record. On the finite ambient it is '
        'one lemma in the kernel’s present character, after new definitions of the operator and its trace. Carrying '
        'the source’s frame to that ambient is not statable there; a Mathlib import is the floor of its price, not a '
        'quote.',
        '',
        '#### The clauses', '',
        'Of b419’s eight kernel-write clauses, three were not meetable as written, not one: `AllPrints.lean` cannot be '
        'append-only, because an import goes before every command. The corrected forms are banked in relay.',
        '',
        '#### The barrier lemma, aimed at positivity', '',
        '**NOT AN INSTANCE, and the failing hypothesis is the proof’s form.** Theorem 3.1 quantifies over formal '
        'first-order proofs whose every step factors through the interface. The arc’s positivity argument is row S1’s '
        'table of constituents at their owners’ grades — measured at cells and on families, imported under the bar, '
        'derived on content, one compiled counting form — and its quantifier over the class is unowned. Aiming at the '
        'right-hand side removed b410’s obstacle, Proposition C.1; it did not remove b407’s. The finite places’ '
        'darkness stands at the keystone’s reading grade and is not supplied by b419’s terminal, which is about the '
        'counting form and not about `W_p`. No entry is written to row U1.',
        '',
        '**The two sentences, side by side.** The lemma: *π can establish "P holds for x in a density-one subset of '
        'each I-class," but cannot certify individual elements.* The aim map: *for zeta the prime sum stays inside the '
        'margin at every aim at this reach — a passed test over a grid at this reach and nothing more.* They are two '
        'facts of two kinds, a bound on proofs and a finite measurement of individual elements. They are consistent, '
        'and they are not one fact.',
        '',
        '#### The four lists', '',
        FOUR,
        '',
        '#### What this act did not do', '',
        '0 grades moved. 0 premises discharged. 0 doors restated. 0 routes proposed. 0 kappa measured. 0 rows of '
        '`FACES_LEDGER.md` written. 0 folds run. 0 rules struck or amended. 0 orientation-layer lines edited. 0 locked '
        'faces edited. 0 prior banks edited. 0 banked ferries edited. 0 bytes of the lock gate or the scan changed. '
        '0 deposit actions, 0 platform calls. **And h2 where the deposit left it.**',
        '',
    ]


SCOPE = ("### THIS ROW RECORDS A RULING EXECUTED, A PROOF CITED IN THE FILE THAT CALLED ITS STATEMENT OPEN, A STEP "
         "PRICED, A FACE'S CLAUSES RE-READ, AND THE CORPUS'S BARRIER LEMMA PUT TO POSITIVITY AND FOUND NOT TO APPLY. "
         "### IT MOVES NO GRADE, DISCHARGES NO PREMISE AND ADDS NO TERMINAL")


def corr_rows():
    m = ("**THE BARRIER LEMMA DOES NOT REACH THE ARC'S POSITIVITY ARGUMENT: NOT AN INSTANCE, ON FORM** "
         "(b420, the lemma aimed)")
    stmt = (m + ". **THE REGISTRATION WAS LOCKED BEFORE ANY WRITE**, chained on b378's gate run as b420 -- @GR@ gates "
            "read, @GDG@ checked by digest. **(R36) ROUTE (1) EXECUTED; THE SCAN-VERSUS-LOCK MISMATCH IS AN INSTRUMENT "
            "ITEM WITH A TRIGGER, NOT OPENED.** **COMPONENT 1: SinglePrimeFactor.lean CITES SmearGeneral.smear_general "
            "AT BOTH PASSAGES THAT CALLED IT OPEN; AND THIS ROW ANNOTATES ROW 263 (b414, " + B414ROW[2:60] + "...), "
            "WHOSE NAMED OPEN STATEMENT IS PROVED AT ROW 268.** **COMPONENT 2: THE STEP TO THE SOURCE'S TRACE IS TWO "
            "PARTS -- ONE LEMMA ON THE FINITE AMBIENT AFTER NEW DEFINITIONS; NOT STATABLE IN THE PRESENT CHARACTER FOR "
            "THE FRAME.** **COMPONENT 3: 3 OF b419'S 8 KERNEL CLAUSES NOT MEETABLE AS WRITTEN.** **COMPONENT 4: THEOREM "
            "3.1'S FIFTH HYPOTHESIS FAILS ON FORM -- THE ARGUMENT IS A TABLE OF GRADED CONSTITUENTS WITH K8 UNOWNED; "
            "THE LEMMA'S REACH AND THE AIM MAP ARE TWO FACTS OF TWO KINDS.** 0 GRADES MOVED, 0 PREMISES DISCHARGED, 0 "
            "CONTENT LOST")
    term = ("NO TERMINAL ADDED OR MOVED. SmearGeneral.smear_general is CITED by Core/SinglePrimeFactor.lean's "
            "annotations; AXIOM_PRINTS.txt regenerated byte-identical, 607 lines")
    prof = ("### ONE KERNEL FILE ANNOTATED BY INSERTION, EVERY WORD AT THE PIN KEPT; AllPrints.lean, FiniteSideSeal.lean "
            "AND SmearGeneral.lean UNCHANGED; NO GRADE, PREMISE, DOOR, KAPPA, ROUTE, FACES_LEDGER ENTRY, FOLD OR RULE "
            "-- 0 CONTENT LOST")
    grade = ("### THE LEMMA'S WORDS WERE QUOTED AND ITS HYPOTHESES READ ONE BY ONE; A FERRY'S DESCRIPTION OF A "
             "TERMINAL WAS PRINTED BESIDE THE TERMINAL AND THE TERMINAL GOVERNED. ### A RESEMBLANCE WAS NOT FILED AS AN "
             "INSTANCE")
    status = ("data/b420_the_lemma_aimed.txt; data/b420_components.txt; data/b420_c1_record.txt; data/b420_c1_verify.txt; "
              "data/b420_c2_priced.txt; data/b420_c3_clauses.txt; data/b420_c4_barrier.txt; "
              "data/b420_registration_2026-09-11.txt (LOCKED at sha256 %s); Core/SinglePrimeFactor.lean; "
              "PLACE-papers OPEN_TRAILS.md; CORRESPONDENCE.md row %%d" % SEALHASH[:16])

    def sub(x):
        return x.replace('@GR@', str(GR)).replace('@GDG@', str(GDG))
    return [(sub(m), sub(stmt), term, prof, grade, SCOPE, status)]


def no_key(out):
    return any(ln.strip().startswith('### NO KEY') for ln in (out or '').splitlines())


def query(qq):
    r = subprocess.run([sys.executable, INDEX, '--query', qq], capture_output=True, text=True,
                       encoding='utf-8', errors='replace')
    return r.stdout or '', r.returncode


ALIASES = ('does the sieve ceiling lemma apply to positivity', 'barrier lemma aimed at positivity', 'the lemma aimed',
           'r36 route one', 'can the trace identification be stated in the kernel', 'b419 kernel clauses not meetable')
MUST_NOT_HIT = ('the lock was overridden', 'the lock gate was changed', 'a grade was moved', 'h2 has moved')
KEY = 'the-lemma-aimed'


def do_key(rownum):
    statement = (
        "b420 PUT THE CORPUS'S BARRIER LEMMA TO POSITIVITY. **NOT AN INSTANCE, ON FORM: THEOREM 3.1 QUANTIFIES OVER "
        "FORMAL FIRST-ORDER PROOFS, AND THE ARC'S POSITIVITY ARGUMENT IS A TABLE OF GRADED CONSTITUENTS WITH ITS CLASS "
        "QUANTIFIER UNOWNED.** Aiming at the right-hand side removed b410's obstacle and not b407's. **THE LEMMA'S "
        "REACH AND THE AIM MAP ARE TWO FACTS OF TWO KINDS.** (R36) ROUTE (1): a scan hit is resolved by re-paste; the "
        "mismatch is an instrument item. SinglePrimeFactor.lean cites the proof; the step to the source's trace is "
        "priced in two parts, PART (ii) not statable in the kernel's present character; 3 of b419's 8 kernel "
        "clauses were not meetable as written.")
    grade = "### NO TERMINAL ADDED OR MOVED, NO GRADE MOVED, NO PREMISE DISCHARGED, NO LEDGER ENTRY. ### NOTHING DEPOSITS"
    where = ("data/b420_the_lemma_aimed.txt; data/b420_c4_barrier.txt; data/b420_c2_priced.txt; data/b420_c3_clauses.txt; "
             "data/b420_c1_record.txt; data/b420_registration_2026-09-11.txt (LOCKED, %d gates read, %d by digest); "
             "CORRESPONDENCE.md row %d" % (GR, GDG, rownum))
    act = "b420 (R36 executed; the proof cited; the reach priced; the clauses re-read; the barrier lemma aimed at positivity)"
    key_new = ("    %r: %r,%s" % (KEY, list(ALIASES), NL))
    row_new = ('    # ### THE LEMMA AIMED (b420).%s    (%r, %r,%s     %r,%s     %r,%s     %r),%s'
               % (NL, KEY, act, NL, statement, NL, grade, NL, where, NL))
    pre = {qq: no_key(query(qq)[0]) for qq in MUST_NOT_HIT}
    for qq in MUST_NOT_HIT:
        rec('    %-40s NO KEY before : %s' % (qq, pre[qq]))
    txt = io.open(INDEX, encoding='utf-8').read()
    KEY_ANCHOR = 'KEYS = {' + NL
    ROW_ANCHOR = ('INDEX = [' + NL + '    # (key, act, one-line statement, grade as its own act recorded it, location)' + NL)
    if KEY_ANCHOR not in txt or ROW_ANCHOR not in txt:
        rec('  ### HARD FAILURE -- an anchor is not in the file.')
        return False
    if ("'%s'" % KEY) not in txt:
        txt = txt.replace(KEY_ANCHOR, KEY_ANCHOR + key_new, 1)
    if ("(%r," % KEY) not in txt:
        txt = txt.replace(ROW_ANCHOR, ROW_ANCHOR + row_new, 1)
    write_bytes(INDEX, txt)
    out, rc = query(KEY)
    n = out.count('act      :')
    ok = (not no_key(out)) and rc == 0 and n >= 1
    rec('  READ BACK : %s returns %d row(s)  %s   [verdict LINE read, under A2]' % (KEY, n, 'PASS' if ok else '### FAIL ###'))
    for qq in ALIASES:
        o, _rc = query(qq)
        g2 = (not no_key(o)) and KEY in o
        ok = ok and g2
        rec('    %-58s reaches the b420 key : %s' % (qq[:58], g2))
    for lbl, cond in (('not an instance, on form', 'NOT AN INSTANCE, ON FORM' in out),
                      ('two facts', 'TWO FACTS OF TWO KINDS' in out),
                      ('route (1)', 'ROUTE (1)' in out),
                      ('part (ii)', 'PART (ii)' in out)):
        ok = ok and cond
        rec('    %-52s : %s' % (lbl, cond))
    for qq in MUST_NOT_HIT:
        o, _rc = query(qq)
        g2 = pre[qq] and no_key(o)
        ok = ok and g2
        rec('    %-40s NO KEY after  : %s' % (qq, no_key(o)))
    rec('  ### %s' % ('PASS' if ok else '### FAIL ###'))
    return ok


def bank_file(Q, rownum, kok):
    B = ['=' * 100, 'b420 -- THE PROOF CITED, THE LOCK RULED, AND THE LEMMA AIMED AT THE RIGHT OBJECT.', 'THE BANK.',
         '=' * 100, '']
    for blk in trail_block():
        if blk and not blk.startswith('<!--'):
            B.append(blk)
    B += ['', '-' * 100, '### THE DESK.', '-' * 100]
    for item, want, _why in DESK:
        B.append('  %-70s %s' % (item[:70], want))
    B += ['', '  ITEMS SWEPT : %d. CLOSED : %d. STANDING : %d.' % (Q['items'], Q['closed'], Q['standing']),
          '', '  CORRESPONDENCE ROW : %d. ### KEY : %s.' % (rownum, 'PASS' if kok else 'FAIL'), '', '=' * 100]
    n = write_bytes(BANKOUT, NL.join(B) + NL)
    rec('  bank written : %s (%d bytes, %d lines)' % (os.path.basename(BANKOUT), n, len(B)))
    return len(B)


def main():
    bar('=')
    rec('b420_desk_bank.py -- THE DESK, THE TRAIL, THE ROW, THE KEY, THE BANK.')
    bar('=')
    if not _g:
        rec('  ### HARD FAILURE -- the lock gate`s permitting record does not carry its count line.')
        return 1
    bar()
    rec('### THE DESK, SWEPT.')
    bar()
    Q = do_desk()
    bar()
    rec('### THE TRAIL, APPENDED.')
    bar()
    t = read(TRAILS)
    if MARK in t:
        rec('  already present; not re-appended.')
    else:
        if PRIOR not in t:
            rec('  ### HARD FAILURE -- the prior act`s mark is absent; refusing to append.')
            return 1
        before = len(t.splitlines())
        t2 = t.rstrip(NL) + NL + NL.join(trail_block()) + NL
        write_bytes(TRAILS, t2)
        rec('  appended %d lines; prior mark still present : %s ; prior text a TRUE PREFIX : %s'
            % (len(t2.splitlines()) - before, PRIOR in t2, t2.startswith(t.rstrip(NL))))
    rec('  lines deleted : 0')
    bar()
    rec('### THE CORRESPONDENCE ROW. ### READ BY MARKER.')
    bar()
    ROWS2 = corr_rows()
    txt = read(TABLE)
    pos, neg = C.blank_check_fixture()
    sa, sb, sc, sd = GD.split_fixture()
    bad = [(i, j) for i, r in enumerate(ROWS2) for j, c in enumerate(r) if GD.raw_pipes(str(c))]
    slip = [mm for mm, s2, *_ in ROWS2 if not s2.startswith(mm)]
    rec('  fixtures %s %s %s %s %s %s ; unescaped pipes %d ; marker a prefix %s' % (pos, neg, sa, sb, sc, sd, len(bad), not slip))
    if bad or slip or not (pos and neg and sa and sb and sc and sd):
        rec('  ### HARD FAILURE at the row fixtures -- nothing written.')
        return 1
    at = lambda mk, s: [int(x.group(1)) for x in re.finditer(r'(?m)^\| (\d+) \| ' + re.escape(mk), s)]
    rec('  b414`s row by its marker : %s ; b419`s : %s' % (at(B414ROW, txt), at(B419ROW, txt)))
    nums = [int(x.group(1)) for x in re.finditer(r'(?m)^\| (\d+) \|', txt)]
    if ROWS2[0][0] in txt:
        rec('  ### ROW ALREADY PRESENT -- NOTHING WRITTEN.')
        rownum = at(ROWS2[0][0], txt)[0]
    else:
        start = max(nums) + 1
        lines = ['| %d | %s | %s | %s | %s %s | %s |' % (start, stmt, term, prof, grade, scope, status % start)
                 for (_m, stmt, term, prof, grade, scope, status) in ROWS2]
        new_txt = txt.rstrip(NL) + NL + NL.join(lines) + NL
        write_bytes(TABLE, new_txt)
        back = read(TABLE)
        got = [int(x.group(1)) for x in re.finditer(r'(?m)^\| (\d+) \|', back)]
        cellsx = [GD.split_cells(t) for t in back.rstrip(NL).split(NL)[-1:]]
        okr = (got[-1] == start and C.blank_cells(back) == 0
               and all(len(c) == 6 and all(x.strip() for x in c) for c in cellsx) and back.startswith(txt.rstrip(NL)))
        rec('  READ BACK : last row %d ; cells %s ; prior text a TRUE PREFIX %s ; %s'
            % (got[-1], [len(c) for c in cellsx], back.startswith(txt.rstrip(NL)), 'PASS' if okr else '### FAIL ###'))
        if not okr:
            return 1
        rownum = start
    after = read(TABLE)
    rec('  after -- b414`s : %s ; b419`s : %s ; this act`s, by its marker : %s'
        % (at(B414ROW, after), at(B419ROW, after), at(ROWS2[0][0], after)))
    bar()
    rec('### THE KEY.')
    bar()
    kok = do_key(rownum)
    bar()
    rec('### THE BANK.')
    bar()
    nlines = bank_file(Q, rownum, kok)
    bar('=')
    rec('  ### ### **DESK %d SWEPT / %d CLOSED. ### CORR ROW %d. ### KEY %s. ### BANK %d LINES.**'
        % (Q['items'], Q['closed'], rownum, 'PASS' if kok else 'FAIL', nlines))
    bar('=')
    io.open(os.path.join(D, 'b420_desk_notes.txt'), 'w', encoding='utf-8', newline=NL).write(NL.join(LINES) + NL)
    return 0 if kok else 1


if __name__ == '__main__':
    sys.exit(main())
