# -*- coding: utf-8 -*-
"""b496_trail.py -- THE TRAIL RECORD. ### **ONE APPEND; PREFIX PROVED, NOT ASSERTED.**"""
import hashlib
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, 'data')
PP = os.path.join('D:', os.sep, 'MY-DOwnloads', 'PLACE-papers')
OT = os.path.join(PP, 'OPEN_TRAILS.md')
NL = chr(10)

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')


def read(p):
    return io.open(p, encoding='utf-8-sig', errors='replace').read().replace(chr(13), '')


HEADING = ('### b496 — (R107) K0: the terminal table generated, '
           'and four matchers to get one number')

BODY = """
%(heading)s

**(R107) ratified.** The keystone refresh programme is opened **as acts, not documents**, in four
checkpoints — **K0** the terminal table generated; **K1** claim-to-row per keystone; **K2**
refresh per keystone; **K3** the monograph's v6 on the object the (R104) sequence leaves. K0 runs
now, while b495's build runs, **because it reads and builds nothing**. K1–K3 wait until the (R104)
acts through h2-as-one-Prop have closed, each ordered by its own ferry. The table K0 emits is an
**INSTRUMENT OUTPUT regenerated at every close by the suite**, filed under `relay/data`, cited by
keystones as a bank; **it is not a tracking document and no prose lives in it.**

**THE TABLE.** `relay/data/terminal_table.json` and `.md`, generated by `tools/terminal_table.py`
over **%(repos)d `SIDE-*` repositories** (all %(repos)d carrying a `.git`) and **%(ledgers)d
ledgers**, the archive's split looms included — b494 found the 2026-07-26 census there, and **a
split moves a ledger, it does not retire it**. One row per `(repo, name)`:

| | |
|:--|:--|
| rows | **%(rows)d** |
| NOT PROFILED | **%(npro)d** |
| UNGRADED | **%(ungr)d** |
| CONFLICT | **%(conf)d** |
| ENCODES-graded | **%(enc)d** |
| ledger names resolving in no repository at any ref | **%(unres)d** |
| STATEMENT UNRESOLVED (kept as a cell, not dropped) | **%(unst)d** |

Every repository is read **as committed blobs**, never through the working tree. The name matcher
is `b378_terminals.py`'s, **imported and not copied**, fixtured on both dialects and both
polarities before use. **No grade is conferred or moved**: each is a ledger cell's, carried with
the act and line that wrote it, and the conflicts are **reported and not resolved**.

**IT TOOK FOUR MATCHERS TO GET ONE NUMBER, AND ALL FOUR YIELDS ARE PRINTED.** v1 took any name on
any line carrying a grade word — **996 cells, 67 CONFLICTS**. v2 bounded it to a table cell and a
120-character window — **221 cells, 17**. v3 attached each grade to its **nearest** name instead
of to every name near it — **164 cells, 12**. v4 read the order again: (R107) defines CONFLICT as
*"two ledger cells grade one name differently"*, and these ledgers routinely write **one** verdict
as `ENCODES-CONCLUSION \\ SHELL` or `SHELL / hypothesis-assumed`; joining adjacent grade words into
a single compound verdict gives **%(cells)d cells, %(conf)d**. **A mention is not a grade cell,
proximity is not attachment, and a compound verdict is not a disagreement.**

**THEN ALL %(conf)d WERE READ BY HAND**, which is the only step that separated signal from noise:
**GENUINE %(ngen)d** (`e_difficulty` — DERIVES at `OPEN_TRAILS-archive-2:939`,
`ENCODES-CONCLUSION \\ SHELL` fourteen lines later at `:953`, INTERFACES in a third place),
**AMBIGUOUS %(namb)d** (`ExplicitFormulaDecomp`, left open rather than decided for the ledger),
**ARTEFACT %(nart)d**. The machine cell stays `CONFLICT` on all %(conf)d — **the instrument
reports what its predicate found, and the hand reading is a separate bank.**

**WHAT THE HAND READING FOUND THAT THE COUNT DID NOT: the grade vocabulary has no cell for a split
grade.** The ledgers write *"DERIVES on the proven direction, INTERFACES on the source
biconditional"* because **one terminal can be two things at once**. The author-ruled taxonomy has
no such cell, so the ledgers improvise one in prose, and **every matcher that reads grades as
atoms misreads them.** A finding for K1; this act neither fixes it nor grades anything.

**`C7_finite_type_false` IS IN THE TABLE, NOT PROFILED** — (R106)(2)'s object, reached by an
instrument that was not told its name, from the other direction, over the whole federation.

**THE REGISTRY NAMES A PIN FOR %(pins)d OF %(repos)d KERNELS.** For the other thirty-eight the
order's *"at the pin REGISTRY cites AND at HEAD"* has **one ref, not two**, and the table says so
per row rather than reading `HEAD` twice and calling it agreement. And **%(ungr)d of %(rows)d rows
carry no grade at all**: the ledgers do not disagree largely because they do not speak.

**Nothing compiled and no `lake` command ran. b495's build at pid 7860 was not polled and its log
was not read — b497 owns it.** Nothing fetched; nothing deposits; nothing at Zenodo written; row
U1 unedited; `h2` where the deposit left it; the four lists stay OPEN. **K1, K2 and K3 are not
started, no keystone was touched, and a table is not a refresh.**
"""


def main():
    T = json.loads(read(os.path.join(D, 'terminal_table.json')))
    R = json.loads(read(os.path.join(D, 'b496_results.json')))
    C = T['counts']

    with open(OT, 'rb') as fh:
        before = fh.read()
    if HEADING in before.decode('utf-8', 'replace'):
        print('### ALREADY PRESENT -- REFUSING A SECOND RECORD.')
        return 2
    body = (BODY % dict(heading=HEADING, repos=T['repos_with_git'], ledgers=T['ledgers'],
                        rows=C['rows'], npro=C['not_profiled'], ungr=C['ungraded'],
                        conf=C['conflict'], enc=C['encodes'],
                        unres=C['ledger_names_unresolved'], unst=C['statement_unresolved'],
                        cells=T['grade_cells'], pins=T['pins_named'],
                        ngen=len(R['genuine']), namb=len(R['ambiguous']),
                        nart=len(R['artefact']))).encode('utf-8')
    with open(OT, 'ab') as fh:
        fh.write(body)
    with open(OT, 'rb') as fh:
        after = fh.read()
    bl = before.decode('utf-8', 'replace').replace(chr(13), '').split(NL)
    al = after.decode('utf-8', 'replace').replace(chr(13), '').split(NL)
    removed = len(bl) - sum(1 for a, b in zip(al, bl) if a == b)
    out = dict(bytes_added=len(after) - len(before), prefix=after.startswith(before),
               lines_removed=removed, headings=after.decode('utf-8', 'replace').count(HEADING),
               before_sha=hashlib.sha256(before).hexdigest(),
               after_sha=hashlib.sha256(after).hexdigest())
    msg = ('OPEN_TRAILS.md : %(bytes_added)d bytes added, prefix %(prefix)s, '
           '%(lines_removed)d lines removed, %(headings)d heading' % out)
    print('  ' + msg)
    json.dump(out, io.open(os.path.join(D, 'b496_trail_notes.json'), 'w',
                           encoding='utf-8', newline=NL), indent=1)
    io.open(os.path.join(D, 'b496_trail_notes.txt'), 'w', encoding='utf-8',
            newline=NL).write(msg + NL)
    return 0 if (out['prefix'] and removed == 0 and out['headings'] == 1) else 1


if __name__ == '__main__':
    sys.exit(main())
