# -*- coding: utf-8 -*-
"""b512_table.py -- COMPONENTS 1-4: THE REGISTER-EQUIVALENCE READ AT h2_sign. ### `python tools/b512_table.py`

### Component 1: one row per form, STATABLE (with the kernel statement quoted from `Registers.lean` / `H2Sign.lean`) or
### NOT STATABLE (with the missing object named and searched for in the kernel's tree). ### Component 2: every ordered
### pair among the STATABLE forms, COMPILED (a theorem at the kernel's pin, named and found), STATABLE-NOT-COMPILED (a
### `Prop` in `Registers.lean`, with the lemmas a proof would need, each FOUND by `git grep`/`grep` or ABSENT), or NOT
### STATABLE. ### Every name printed as FOUND is searched for, never typed as present.
"""
import io
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, 'data')
KER = os.path.join('D:', os.sep, 'SIDE-explicit-formula')
ML = os.path.join(KER, '.lake', 'packages', 'mathlib')
NL = chr(10)
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')


def kernel_text():
    out = {}
    for dp, _d, fs in os.walk(KER):
        if '.lake' in dp or '.git' in dp:
            continue
        for f in fs:
            if f.endswith('.lean'):
                p = os.path.join(dp, f)
                out[os.path.relpath(p, KER).replace(os.sep, '/')] = io.open(p, encoding='utf-8').read()
    return out


KT = kernel_text()


def in_kernel(name):
    last = name.split('.')[-1]
    pat = re.compile(r'^\s*(?:@\[[^\]]*\]\s*)?(?:theorem|lemma|def)\s+%s\b' % re.escape(last), re.M)
    return sorted(f for f, t in KT.items() if pat.search(t))


def in_mathlib(name):
    ns, last = (name.rsplit('.', 1) + [''])[:2] if '.' in name else ('', name)
    r = subprocess.run(['git', '-C', ML, 'grep', '-l', '-E', r'^\s*(theorem|lemma|def|instance)\s+(%s\.)?%s\b' % (re.escape(ns.split('.')[-1]) if ns else '[A-Za-z_]*', re.escape(last)),
                        '--', 'Mathlib'], capture_output=True, text=True, encoding='utf-8', errors='replace')
    hits = [l for l in r.stdout.split(NL) if l.strip()]
    if not hits:
        # ### a name GENERATED by `to_additive` has no declaration line of its own (b512: `tsum_nonneg`)
        r2 = subprocess.run(['git', '-C', ML, 'grep', '-l', '-E', 'to_additive.*[^A-Za-z_]%s([^A-Za-z_0-9]|$)' % re.escape(last), '--', 'Mathlib'],
                            capture_output=True, text=True, encoding='utf-8', errors='replace')
        hits = ['(to_additive) ' + l for l in r2.stdout.split(NL) if l.strip()]
    return hits


def found(where, name):
    hits = in_kernel(name) if where == 'kernel' else in_mathlib(name)
    if where == 'mathlib' and '.' in name:
        # ### b512`s own defect, repaired: the namespace was optional in the pattern, so an unqualified match in ANOTHER
        # ### namespace (Quaternion`s `normSq_nonneg`) was printed as the file. Files that open the named namespace first.
        ns = name.rsplit('.', 1)[0].split('.')[-1]
        own = [h for h in hits if ('namespace %s' % ns) in io.open(os.path.join(ML, h.replace('(to_additive) ', '')), encoding='utf-8', errors='replace').read()]
        hits = own
    return dict(name=name, where=where, found=bool(hits), files=hits[:2])


def stmt(name):
    """### the declaration as the module prints it, from its line to the next blank line."""
    for f, t in KT.items():
        m = re.search(r'^(?:def|theorem) %s\b' % re.escape(name), t, re.M)
        if m and f.startswith('SIDEExplicitFormula/'):
            j = t.find(NL + NL, m.start())
            return t[m.start():j if j >= 0 else len(t)].strip(), f
    return None, None


SEARCH_ABSENT = {
    'silence_universal': ['silence_universal', 'SilenceTheorem', 'behavioral'],
    'ConservationHypothesis': ['ConservationHypothesis', 'EulerBalance', 'euler_balance'],
    'mechanism realization': ['Mechanism', 'mechanism', 'realization'],
    'spectral realization operator': ['HilbertPolya', 'selfAdjoint.*spectrum', 'zeroRealizing'],
    'archimedean Li channel lambda_A': ['lambda_A', 'liArch', 'LiCoeff', 'Li coefficient'],
    'Weil positivity criterion': ['Weil.*criterion', 'weil_criterion', 'WeilPositivity'],
    'Li criterion': ['li_criterion', 'LiCriterion', 'Keiper'],
}


def grep_absent(keys):
    """### each missing object searched in the kernel's own tree AND its Mathlib; the yields printed."""
    out = []
    for k in keys:
        kh = sum(1 for t in KT.values() if re.search(k, t))
        r = subprocess.run(['git', '-C', ML, 'grep', '-l', '-E', k, '--', 'Mathlib'], capture_output=True, text=True,
                           encoding='utf-8', errors='replace')
        out.append(dict(needle=k, kernel_files=kh, mathlib_files=len([l for l in r.stdout.split(NL) if l.strip()])))
    return out


def main():
    rows1 = [
        ('R1', 'register 1: universality of silence_universal', 'NOT STATABLE', 'silence_universal',
         'the universal-interface objects and the behavioral parameter kappa live in SIDE-kernel; this kernel neither defines nor imports them, and the federation forbids a Lake cross-dependency'),
        ('R2', 'register 2: the ConservationHypothesis of Route 3', 'NOT STATABLE', 'ConservationHypothesis',
         'the Euler balance equation at a prime, SIDE-kernel`s definition; absent from this kernel'),
        ('R3', 'register 3: totality of realization through places', 'NOT STATABLE', 'mechanism realization',
         'the mechanisms and the place-to-mechanism reflection are category-shaped objects of the corpus, with no formal counterpart here'),
        ('R4', 'register 4: the balance-to-positivity distance at the multiplicative place', 'STATABLE', 'h2_sign',
         'its sign form IS h2_sign; the DISTANCE as a number is not defined in the kernel -- the row states the sign form only'),
        ('R5', 'register 5: the spectral-realization distance', 'NOT STATABLE', 'spectral realization operator',
         'no operator, spectrum or realization map exists in this kernel'),
        ('LI2', 'the two-channel Li form lambda_Z(n) >= -lambda_A(n)', 'NOT STATABLE', 'archimedean Li channel lambda_A',
         'the archimedean channel lambda_A is not constructed here; ITS SUM lambda_n >= 0 IS STATABLE, as li_form'),
        ('LI', 'Li`s criterion, single-channel, lambda_n >= 0', 'STATABLE', 'li_form', ''),
        ('CELL', 'the cell form m(a) >= 0 on an admissible family', 'STATABLE', 'cell_form',
         'the family is a PARAMETER: the ladder`s B-spline windows are not constructed as Lean functions'),
        ('RH', 'RH as Mathlib states it', 'STATABLE', 'rh_form', ''),
        ('H2', 'h2_sign', 'STATABLE', 'h2_sign', ''),
    ]
    C1 = []
    for key, what, status, obj, note in rows1:
        r = dict(key=key, form=what, status=status, note=note)
        if status == 'STATABLE':
            r['statement'], r['file'] = stmt(obj)
            r['status'] = 'STATABLE' if r['statement'] else 'NOT FOUND IN THE MODULE'
        else:
            r['missing'] = obj
            r['search'] = grep_absent(SEARCH_ABSENT[obj])
        C1.append(r)
    RH_H2 = [found('kernel', 'paperFT_weilTest'), found('kernel', 'zetaZeroConfig_carrier'), found('kernel', 'RH_implies_on_line'),
             found('kernel', 'b321_identity'), found('mathlib', 'Complex.mul_conj'), found('mathlib', 'Complex.normSq_nonneg'),
             found('mathlib', 'tsum_nonneg'), found('mathlib', 'Complex.orderClosedTopology')]
    WEIL = [dict(name='a Weil-criterion construction (a K-window concentrated at an off-line zero)', where='kernel+mathlib',
                 found=False, files=[], search=grep_absent(SEARCH_ABSENT['Weil positivity criterion']))]
    LI = [dict(name='Li`s criterion and the summability of liCoeff', where='kernel+mathlib', found=False, files=[],
               search=grep_absent(SEARCH_ABSENT['Li criterion']))]
    DENS = [dict(name='a density argument: the family`s windows span the Weil form on classK', where='kernel+mathlib',
                 found=False, files=[])]
    C2 = [
        ('H2 -> RH', 'h2_imp_rh', 'STATABLE-NOT-COMPILED', WEIL),
        ('RH -> H2', 'rh_imp_h2', 'STATABLE-NOT-COMPILED', RH_H2),
        ('RH -> LI', 'rh_imp_li', 'STATABLE-NOT-COMPILED', LI),
        ('LI -> RH', 'li_imp_rh', 'STATABLE-NOT-COMPILED', LI),
        ('H2 -> LI', 'h2_imp_li', 'STATABLE-NOT-COMPILED', WEIL + LI),
        ('LI -> H2', 'li_imp_h2', 'STATABLE-NOT-COMPILED', LI + RH_H2),
        ('H2 -> CELL', 'h2_sign_imp_cell', 'COMPILED', []),
        ('CELL -> H2', 'cell_imp_h2', 'STATABLE-NOT-COMPILED', DENS),
        ('RH -> CELL', 'rh_imp_cell', 'STATABLE-NOT-COMPILED', RH_H2),
        ('CELL -> RH', 'cell_imp_rh', 'STATABLE-NOT-COMPILED', DENS + WEIL),
        ('LI -> CELL', 'li_imp_cell', 'STATABLE-NOT-COMPILED', LI + RH_H2),
        ('CELL -> LI', 'cell_imp_li', 'STATABLE-NOT-COMPILED', DENS + WEIL + LI),
    ]
    rows2 = []
    for pair, name, status, needs in C2:
        st, f = stmt(name)
        rows2.append(dict(pair=pair, name=name, status=status if st else 'MISSING FROM THE MODULE', statement=st,
                          needs=needs, all_found=all(n['found'] for n in needs) if needs else True))
    weakest = [r['pair'].split(' -> ')[1] for r in rows2
               if r['pair'].startswith('H2 -> ') and r['status'] == 'COMPILED'
               and not any(x['pair'] == r['pair'].split(' -> ')[1] + ' -> H2' and x['status'] == 'COMPILED' for x in rows2)]
    res = dict(C1=C1, C2=rows2, weakest=weakest)
    L = ['=' * 104, 'b512 -- THE REGISTER-EQUIVALENCE READ AT h2_sign.', '=' * 104, '### COMPONENT 1 -- THE FORMS.']
    for r in C1:
        L.append('  %-4s %-72s %s' % (r['key'], r['form'][:72], r['status']))
        if r.get('statement'):
            L += ['       ' + x for x in r['statement'].split(NL)] + ['       <%s>' % r['file']]
        if r.get('missing'):
            L.append('       MISSING : %s -- %s' % (r['missing'], r['note']))
            L.append('       searched : ' + ' ; '.join('%(needle)s kernel %(kernel_files)d / Mathlib %(mathlib_files)d files' % s for s in r['search']))
        elif r['note']:
            L.append('       ### %s' % r['note'])
    L += ['', '### COMPONENT 2 -- THE ORDERED IMPLICATIONS AMONG H2, RH, LI (single-channel) AND CELL. ### R4 IS H2 ITSELF.']
    for r in rows2:
        L.append('  %-12s %-24s %s' % (r['pair'], r['status'], r['name']))
        for n in r['needs']:
            L.append('       needs %-78s %s' % (n['name'][:78], ('FOUND ' + ', '.join(n['files'])) if n['found'] else 'ABSENT'))
            for s in n.get('search', []):
                L.append('             searched %(needle)s : kernel %(kernel_files)d / Mathlib %(mathlib_files)d files' % s)
    L += ['', '### COMPONENT 3 -- THE WEAKEST FORM: implied by h2_sign by a COMPILED step, and with no compiled route back :',
          '    %s' % (weakest or 'NONE'),
          '    ### "DOES NOT IMPLY" IS A STATEMENT ABOUT DERIVABILITY IN THIS KERNEL, NOT A THEOREM: if RH holds, every form here is',
          '    true and every implication holds trivially. What the table shows is that no route back is available here.',
          '=' * 104]
    io.open(os.path.join(D, 'b512_table.txt'), 'w', encoding='utf-8', newline=NL).write(NL.join(L) + NL)
    io.open(os.path.join(D, 'b512_table.json'), 'w', encoding='utf-8', newline=NL).write(json.dumps(res, indent=1, ensure_ascii=False) + NL)
    print(NL.join(L))
    return 0


if __name__ == '__main__':
    sys.exit(main())
