# -*- coding: utf-8 -*-
"""b563_findsup_test.py -- COMPONENT 1: THE FINDINGS-LINE SUPERSESSION FORM, ITS TEST, UNDER (R173)(3).
### `python tools/b563_findsup_test.py unit | noop | after`. ### unit: fixtures on supplied cells, both polarities.
### noop / after: the table regenerated by `tools/terminal_table.py` and compared with the committed table at relay HEAD
### (b562's housekeeping) -- rows, CONFLICT before and after, terminals whose grade changed, li_identity_of_exchange's cells.
### This file deletes nothing.
"""
import io, json, os, subprocess, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D, T = os.path.join(ROOT, 'data'), os.path.join(ROOT, 'tools')
sys.path.insert(0, T)
NL = chr(10)
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
TERM = 'li_identity_of_exchange'


def put(name, L):
    io.open(os.path.join(D, name), 'w', encoding='utf-8', newline=NL).write(NL.join(L) + NL)
    print(NL.join(L))


def unit():
    import terminal_table as TT
    F = TT.FIND_LABEL
    cells = [dict(grade='INTERFACES', ledger=F, line=6048), dict(grade='SHELL', ledger=TT.CORR_LABEL, line=470),
             dict(grade='INTERFACES', ledger=F, line=9000), dict(grade='DERIVES', ledger=F, line=7000)]
    L = ['b563 -- COMPONENT 1 (i): THE FINDINGS-LINE FORM, UNIT FIXTURES ON SUPPLIED CELLS, BOTH POLARITIES', '']
    cases = []

    def run(label, directives, name, expect):
        TT._FIND_DIRECTIVES[:] = directives + [None]
        got = [(c['ledger'].split('/')[-1], c['line']) for c in TT.supersede_findings(cells, name)]
        ok = got == expect
        cases.append(ok)
        L.append('  %-78s %s' % (label, 'AGREES' if ok else '### DISAGREES %s' % got))
    allc = [(c['ledger'].split('/')[-1], c['line']) for c in cells]
    run('fires: :6048 named for the terminal (qualified name) -- :6048 and the directive`s own line 9000 gone',
        [(6048, TERM, F, 9000)], 'SIDEExplicitFormula.LiWeil.' + TERM, [('CORRESPONDENCE.md', 470), ('FINDINGS.md', 7000)])
    run('fires: the short name as the table`s name', [(6048, TERM, F, 9000)], TERM, [('CORRESPONDENCE.md', 470), ('FINDINGS.md', 7000)])
    run('quiet: a directive naming another terminal removes nothing', [(6048, 'other_terminal', F, 9000)], TERM, allc)
    run('quiet: no directive at all', [], TERM, allc)
    run('quiet on other lines: a directive for :7001 removes only its own line`s cell', [(7001, TERM, F, 9000)], TERM,
        [('FINDINGS.md', 6048), ('CORRESPONDENCE.md', 470), ('FINDINGS.md', 7000)])
    run('quiet on another ledger: FINDINGS :470 does not reach CORRESPONDENCE :470', [(470, TERM, F, 9000)], TERM,
        [('FINDINGS.md', 6048), ('CORRESPONDENCE.md', 470), ('FINDINGS.md', 7000)])
    TT._FIND_DIRECTIVES[:] = []
    L.append('')
    L.append('### ### **FIXTURES %d ; AGREEING %d : %s**' % (len(cases), sum(cases), 'PASS' if all(cases) else 'FAIL'))
    put('b563_findsup_unit.txt', L)
    return 0 if all(cases) else 1


def table_rows(j):
    rows = j['rows'] if isinstance(j, dict) else j
    return {(r['repo'], r['name']): r for r in rows}


def regen(name, title):
    before = table_rows(json.loads(subprocess.run(['git', '-C', ROOT, 'show', 'HEAD:data/terminal_table.json'],
                                                  capture_output=True).stdout.decode('utf-8')))
    r = subprocess.run([sys.executable, os.path.join(T, 'terminal_table.py')], capture_output=True, text=True, encoding='utf-8', errors='replace')
    after = table_rows(json.loads(io.open(os.path.join(D, 'terminal_table.json'), encoding='utf-8').read()))
    run = io.open(os.path.join(D, 'terminal_table_run.txt'), encoding='utf-8').read()
    cb = sorted('%s|%s' % k for k, v in before.items() if v['grade'] == 'CONFLICT')
    ca = sorted('%s|%s' % k for k, v in after.items() if v['grade'] == 'CONFLICT')
    changed = sorted('%s|%s %s -> %s' % (k[0], k[1], before[k]['grade'], after[k]['grade']) for k in before if k in after and before[k]['grade'] != after[k]['grade'])
    L = ['b563 -- COMPONENT 1 (%s): %s' % (name, title), '',
         '### regenerated: exit %d ; rows %d (before %d) ; rows gone %s ; rows added %s' % (
             r.returncode, len(after), len(before), sorted('%s|%s' % k for k in before if k not in after) or 'NONE',
             sorted('%s|%s' % k for k in after if k not in before) or 'NONE'),
         '### the run`s header: ' + ([l.strip() for l in run.split(NL) if 'FINDINGS-LINE SUPERSESSIONS READ' in l] or ['### ABSENT'])[0],
         '### ### **CONFLICT before %d -> after %d**' % (len(cb), len(ca)), '### CONFLICT before (%d):' % len(cb)] + ['    ' + x for x in cb] + \
        ['### CONFLICT after (%d):' % len(ca)] + ['    ' + x for x in ca] + \
        ['### ### **TERMINALS WHOSE GRADE CHANGED : %s**' % (changed or 'NONE')]
    for lab, tab in (('before', before), ('after', after)):
        for k, v in tab.items():
            if k[1].endswith(TERM):
                L.append('### %s -- %s|%s grade %s' % (lab, k[0], k[1], v['grade']))
                L += ['    cell %-22s %s:%s' % (c['grade'], c['ledger'], c['line']) for c in v['grade_cells']]
    tag = 'noop' if name == 'ii' else 'after'   # ### b563 defect (d): `startswith('ii')` matched 'iii' and banked the after run as noop
    put('b563_findsup_%s.txt' % tag, L)
    json.dump(dict(rc=r.returncode, rows=len(after), conflict_before=cb, conflict_after=ca, changed=changed,
                   term={lab: [dict(grade=c['grade'], ledger=c['ledger'], line=c['line']) for k, v in tab.items() if k[1].endswith(TERM)
                               for c in v['grade_cells']] for lab, tab in (('before', before), ('after', after))},
                   term_grade={lab: [v['grade'] for k, v in tab.items() if k[1].endswith(TERM)] for lab, tab in (('before', before), ('after', after))}),
              io.open(os.path.join(D, 'b563_findsup_%s.json' % tag), 'w', encoding='utf-8', newline=NL),
              indent=1, ensure_ascii=False)
    return r.returncode


if __name__ == '__main__':
    c = sys.argv[1] if len(sys.argv) > 1 else ''
    if c == 'unit':
        sys.exit(unit())
    if c == 'noop':
        sys.exit(regen('ii', 'THE TABLE REGENERATED BEFORE THE LINE EXISTS (the parser alone)'))
    if c == 'after':
        sys.exit(regen('iii', 'THE TABLE REGENERATED AFTER THE LINE AT FINDINGS'))
    sys.exit('usage: b563_findsup_test.py unit | noop | after')
