# -*- coding: utf-8 -*-
"""b564_generic_gen.py -- READING (6)(b): THE LEAN SCAN'S YIELD FILTERED AND BANKED, AND `Chi/Generic.lean` GENERATED FROM IT.
### `python tools/b564_generic_gen.py <raw scan output> [<out lean file>]`. The raw output is the `run_cmd` scan's messages; the
### bank keeps every constant it listed and marks the auxiliary ones (equation lemmas, recursors, constructors, projections of
### the structure itself) as not consumer declarations, with the reason. Writes relay data/b564_generic_leanscan.* and, when
### asked, the generated file. Deletes nothing.
"""
import io, json, os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, 'data')
NL = chr(10)
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

AUX = re.compile(r'\.(eq_\d+|eq_def|noConfusion|noConfusionType|rec|recOn|casesOn|brecOn|below|ibelow|binductionOn|mk|injEq|inj|'
                 r'sizeOf_spec|ext|ext_iff|mk\.injEq|mk\.inj|mk\.sizeOf_spec)$')
FIELDS = {'carrier', 'mult', 'one_le_mult', 'strip', 'reflect_mem', 'mult_reflect', 'finite_window'}


def parse(raw):
    flat = re.sub(r'\s+', ' ', raw)
    out = []
    for m in re.finditer(r'B564SCAN (\S+) (\S+) (\S+) pos=(none|some \((\d+)\)) before=\[([^\]]*)\]', flat):
        out.append(dict(module=m.group(1), name=m.group(2), kind=m.group(3),
                        pos=None if m.group(4) == 'none' else int(m.group(5)),
                        before=[x.strip() for x in m.group(6).split(',') if x.strip()]))
    return out


def classify(c):
    n = c['name']
    if AUX.search(n):
        return 'AUXILIARY (generated by Lean: %s)' % AUX.search(n).group(1)
    if n.startswith('Zeta23.ZeroConfig.') and n.split('.')[-1] in FIELDS:
        return 'THE STRUCTURE`S OWN FIELD (a projection; the instance supplies it)'
    if n == 'Zeta23.ZeroConfig':
        return 'THE STRUCTURE ITSELF'
    if c['pos'] is None:
        return 'NO ZeroConfig BINDER (the type names ZeroConfig inside a binder`s type or the conclusion)'
    return 'CONSUMER'


def sanitize(n):
    return 'chi_' + n.replace('Zeta23.', '').replace('.', '_').replace("'", '_')


def gen(cons):
    head = ['/-', 'SIDE-explicit-formula -- SIDEExplicitFormula/Chi/Generic.lean',
            "THIS PROGRAMME'S WORK (act b564, ruling (R174)(5)(b); W-ORD-GRH-WEIL, act two) -- NOT VENDORED.",
            'SPIRAL_MAP section 7 rule 9 applies here in full: `theorem`, never `lemma`.', '',
            'THE GENERIC MODULES CONSUMED BY THE χ-INSTANCE. Every Zeta23 module the DAG bank classes GENERIC is imported below,',
            'unedited, and every top-level declaration of those modules whose type has a binder of type `Zeta23.ZeroConfig`',
            '(found by a `run_cmd` scan over the environment, relay data/b564_generic_leanscan.txt) is applied to `chiZeroConfig`.',
            'Each `chi_<name>` has the type of that application (`type_of%`) and the application as its body: nothing is',
            're-proved, nothing copied. GENERATED by relay tools/b564_generic_gen.py; not edited by hand.', '',
            'Nothing here proves GRH, RH, or any statement about the zeros of `LFunction χ` beyond these instantiations.', '-/',
            'import SIDEExplicitFormula.Chi.ZeroConfig']
    mods = sorted(set(json.loads(io.open(os.path.join(D, 'b564_dag.json'), encoding='utf-8').read())['generic']))
    head += ['import %s' % m for m in mods]
    head += ['', 'noncomputable section', '', 'namespace SIDEExplicitFormula', 'namespace GRHWeil', 'namespace Generic', '',
             'open DirichletCharacter', '', 'variable {N : ℕ} [NeZero N]', '']
    body = []
    for c in cons:
        cfg = '(chiZeroConfig χ hχ h1)'
        # ### b564 attempt b_1: a binder BEFORE the ZeroConfig one cannot be left as `_` (Lean cannot synthesize it); it is
        # ### abstracted as a lambda parameter, so the instantiation is a function of those arguments.
        if c['pos']:
            xs = ' '.join('x%d' % i for i in range(c['pos']))
            app = '(fun %s => @%s %s %s)' % (' '.join('(x%d : _)' % i for i in range(c['pos'])), c['name'], xs, cfg)
        else:
            app = '@%s %s' % (c['name'], cfg)
        kw = 'theorem' if c['kind'] == 'theorem' else 'def'
        body += ['/-- `%s` (%s) at the χ-instance. -/' % (c['name'], c['module']),
                 '%s %s (χ : DirichletCharacter ℂ N) (hχ : χ.IsPrimitive) (h1 : χ ≠ 1) :' % (kw, sanitize(c['name'])),
                 '    type_of%% (%s) :=' % app, '  %s' % app, '']
    tail = ['end Generic', 'end GRHWeil', 'end SIDEExplicitFormula']
    return NL.join(head + body + tail) + NL


def main(argv):
    raw = io.open(argv[0], encoding='utf-8', errors='replace').read()
    cs = parse(raw)
    for c in cs:
        c['class'] = classify(c)
    cs.sort(key=lambda c: (c['module'], c['name']))
    cons = [c for c in cs if c['class'] == 'CONSUMER']
    L = ['b564 -- READING (6)(b): THE LEAN SCAN (a `run_cmd` over the environment importing the generic modules) -- ITS YIELD',
         '### every constant declared in a generic module whose type mentions Zeta23.ZeroConfig: %d ; consumer declarations %d' % (len(cs), len(cons)),
         '### the raw run: exit 1 on one parse error the seat wrote (a doc comment before `run_cmd`, stdin:43), recovered by Lean;',
         '### the command ran and printed every line below.', '']
    for c in cs:
        L.append('  %-28s %-60s %-9s pos %-4s %s' % (c['module'][7:], c['name'], c['kind'], c['pos'], c['class']))
    bym = {}
    for c in cons:
        bym.setdefault(c['module'], []).append(c['name'])
    L += ['', '### CONSUMERS BY MODULE (%d modules):' % len(bym)] + ['    %s : %d' % (m, len(v)) for m, v in sorted(bym.items())]
    io.open(os.path.join(D, 'b564_generic_leanscan.txt'), 'w', encoding='utf-8', newline=NL).write(NL.join(L) + NL)
    json.dump(dict(all=cs, consumers=cons), io.open(os.path.join(D, 'b564_generic_leanscan.json'), 'w', encoding='utf-8', newline=NL),
              ensure_ascii=False, indent=1)
    print(NL.join(L[:2] + L[-len(bym) - 1:]))
    if len(argv) > 1:
        io.open(argv[1], 'w', encoding='utf-8', newline=NL).write(gen(cons))
        print('generated: %s (%d declarations)' % (argv[1], len(cons)))


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
