# -*- coding: utf-8 -*-
"""b564_axiomcheck_gen.py -- READING (7): `AxiomCheckChi.lean` GENERATED FROM THE BRANCH TIP'S OWN FILES (their declarations,
read by a regex over each file at the committed tip), and the declaration list banked. Writes the one kernel file on the branch
(new) and relay data/b564_decls.json. Deletes nothing.
"""
import io, json, os, re, subprocess, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, 'data')
EF = os.path.join('D:' + os.sep, 'SIDE-explicit-formula')
NL = chr(10)
FILES = [('SIDEExplicitFormula/Chi/ZeroConfig.lean', 'SIDEExplicitFormula.GRHWeil.'),
         ('SIDEExplicitFormula/Chi/Generic.lean', 'SIDEExplicitFormula.GRHWeil.Generic.'),
         ('SIDEExplicitFormula/Chi/ZetaBounds.lean', 'SIDEExplicitFormula.GRHWeil.')]
DECL = re.compile(r'^(theorem|def|noncomputable def|abbrev)\s+([^\s(:{\[]+)', re.M)


def main():
    decls = []
    for rel, ns in FILES:
        t = subprocess.run(['git', '-C', EF, 'show', 'HEAD:' + rel], capture_output=True).stdout.decode('utf-8')
        for m in DECL.finditer(t):
            decls.append(dict(file=rel, kind='theorem' if m.group(1) == 'theorem' else 'def', name=ns + m.group(2),
                              line=t.count(NL, 0, m.start()) + 1))
    src = ['import SIDEExplicitFormula.Chi.Generic', 'import SIDEExplicitFormula.Chi.ZetaBounds', '',
           '/-!', '# Axiom audit -- GRH-Weil act two: the χ-instance, the generic modules consumed, the frontier`s ZetaBounds analogues',
           '(act b564, ruling (R174)(5))', '',
           'Run `lake env lean AxiomCheckChi.lean` (once the modules are built) to reproduce the `#print axioms` output for every',
           'declaration of `SIDEExplicitFormula/Chi/*.lean`, and the `#print` of each definition (the salt-check). Each is expected to',
           'reduce to the standard base (`propext`, `Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output',
           'is the verdict, not this comment. GENERATED by relay tools/b564_axiomcheck_gen.py from the branch tip`s files.', '-/', '']
    src += ['#print axioms %s' % d['name'] for d in decls]
    src += [''] + ['#print %s' % d['name'] for d in decls if d['kind'] == 'def']
    io.open(os.path.join(EF, 'AxiomCheckChi.lean'), 'w', encoding='utf-8', newline=NL).write(NL.join(src) + NL)
    json.dump(decls, io.open(os.path.join(D, 'b564_decls.json'), 'w', encoding='utf-8', newline=NL), ensure_ascii=False, indent=1)
    by = {}
    for d in decls:
        by.setdefault((d['file'], d['kind']), 0)
        by[(d['file'], d['kind'])] += 1
    print('declarations %d : %s' % (len(decls), by))


if __name__ == '__main__':
    sys.exit(main())
