# -*- coding: utf-8 -*-
"""b566_axiomcheck_gen.py -- READING (5): `AxiomCheckLiCriterion.lean` GENERATED FROM THE BRANCH TIP'S OWN FILES -- every
declaration of SIDEExplicitFormula/LiCriterionBridge.lean (read by a regex over the file at the route branch's committed tip, vendor-bulka-forward-b566), then the vendored
terminals the module consumes by name, then `#check` of the two composed theorems (their statements as Lean prints them) and
`#print` of each definition (the salt-check). Writes the one kernel file on the branch (new) and relay data/b566_decls.json.
Deletes nothing.
"""
import io, json, os, re, subprocess, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, 'data')
EF = os.path.join('D:' + os.sep, 'SIDE-explicit-formula')
TREE = os.path.join('D:' + os.sep, 'b566-forward')   # ### the route's worktree (trial (b), named the route)
REV = 'vendor-bulka-forward-b566'
NL = chr(10)
REL = 'SIDEExplicitFormula/LiCriterionBridge.lean'
NS = 'SIDEExplicitFormula.LiCriterionBridge.'
DECL = re.compile(r'^(theorem|def|noncomputable def|abbrev)\s+([^\s(:{\[]+)', re.M)
CONSUMED = ['LiCriterion.positivity_implies_RH', 'LiCriterion.taylorCoeff_eq_li_symmetrized', 'LiCriterion.summable_li_symmetrized',
            'LiCriterion.rh_equiv_mathlib', 'LiCriterion.liSummand_pairedZero', 'LiCriterion.analyticOrderNatAt_riemannXi_one_sub',
            'LiCriterion.pairedZero_involutive', 'XiZeros.xi_eq_half_s_sm1_Lambda',
            'SIDEExplicitFormula.LiWeil.rh_imp_li_nonneg', 'SIDEExplicitFormula.LiWeil.li_identity_sym',
            'SIDEExplicitFormula.LiWeil.LiCoeff_eq', 'SIDEExplicitFormula.LiWeil.liTerm_re_summable']


def main():
    t = subprocess.run(['git', '-C', EF, 'show', REV + ':' + REL], capture_output=True).stdout.decode('utf-8')
    if not t:
        print('### %s IS NOT AT THE TIP OF %s: refusing' % (REL, REV))
        return 2
    decls = [dict(file=REL, kind='theorem' if m.group(1) == 'theorem' else 'def', name=NS + m.group(2),
                  line=t.count(NL, 0, m.start()) + 1) for m in DECL.finditer(t)]
    src = ['import SIDEExplicitFormula.LiCriterionBridge', '',
           '/-!', '# Axiom audit -- the converse composed: the equality lemma, li_nonneg_iff_rh and arith_limit_nonneg_iff_rh',
           '(act b566, ruling (R176)(3))', '',
           'Run `lake env lean AxiomCheckLiCriterion.lean` (once the modules are built) to reproduce the `#print axioms` output for',
           'every declaration of `SIDEExplicitFormula/LiCriterionBridge.lean` and for the vendored and kernel terminals it consumes',
           'by name, the `#check` of the two composed theorems, and the `#print` of each definition (the salt-check). Each is',
           'expected to reduce to the standard base (`propext`, `Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The',
           'compiler`s output is the verdict, not this comment. GENERATED by relay tools/b566_axiomcheck_gen.py from the branch tip.',
           '-/', '']
    src += ['#print axioms %s' % d['name'] for d in decls]
    src += [''] + ['#print axioms %s' % n for n in CONSUMED]
    src += ['', '#check @%sli_nonneg_iff_rh' % NS, '#check @%sarith_limit_nonneg_iff_rh' % NS, '#check @%sli_coeff_eq_taylorCoeff' % NS]
    src += [''] + ['#print %s' % d['name'] for d in decls if d['kind'] == 'def']
    io.open(os.path.join(TREE, 'AxiomCheckLiCriterion.lean'), 'w', encoding='utf-8', newline=NL).write(NL.join(src) + NL)
    json.dump(dict(decls=decls, consumed=CONSUMED), io.open(os.path.join(D, 'b566_decls.json'), 'w', encoding='utf-8', newline=NL),
              ensure_ascii=False, indent=1)
    print('declarations %d (theorems %d, defs %d) ; consumed %d' % (len(decls), sum(d['kind'] == 'theorem' for d in decls),
                                                                  sum(d['kind'] == 'def' for d in decls), len(CONSUMED)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
