# -*- coding: utf-8 -*-
"""b567_axiomcheck_gen.py -- READING (6): AN AxiomCheck FILE GENERATED FROM A BRANCH TIP'S OWN FILES.
### `python tools/b567_axiomcheck_gen.py residue` -> AxiomCheckResidue.lean (ResidueDischarge.lean at residue-discharge-b567);
### `python tools/b567_axiomcheck_gen.py chi`     -> AxiomCheckChiStrip.lean (Chi/ZetaBoundsStrip.lean and Chi/Statement.lean
### at grh-weil-b567). Every declaration of the files (a regex over the file AT THE BRANCH'S COMMITTED TIP, never the working
### tree), then the terminals they consume by name, the `#check` of the named statements and the `#print` of each definition.
### Writes the one kernel file in the checkout and relay data/b567_decls_<which>.json. Deletes nothing.
"""
import io, json, os, re, subprocess, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, 'data')
EF = os.path.join('D:' + os.sep, 'SIDE-explicit-formula')
NL = chr(10)
DECL = re.compile(r'^(theorem|def|noncomputable def|abbrev)\s+([^\s(:{\[]+)', re.M)
SETS = {
    'residue': dict(
        rev='residue-discharge-b567', out='AxiomCheckResidue.lean',
        files=[('SIDEExplicitFormula/ResidueDischarge.lean', 'SIDEExplicitFormula.ResidueDischarge.')],
        imports=['SIDEExplicitFormula.ResidueDischarge'],
        title='the residue chain`s Li-channel premise discharged: (L1)-(L3) (act b567, ruling (R177)(5))',
        consumed=['SIDEExplicitFormula.LiCriterionBridge.li_nonneg_iff_rh', 'SIDEExplicitFormula.LiWeil.LiCoeff_eq'],
        check=['SIDEExplicitFormula.ResidueDischarge.register4_positivity_liCoeff_imp_rh',
               'SIDEExplicitFormula.ResidueDischarge.liCoeff_zero']),
    'chi': dict(
        rev='grh-weil-b567', out='AxiomCheckChiStrip.lean',
        files=[('SIDEExplicitFormula/Chi/ZetaBoundsStrip.lean', 'SIDEExplicitFormula.GRHWeil.'),
               ('SIDEExplicitFormula/Chi/Statement.lean', 'SIDEExplicitFormula.GRHWeil.')],
        imports=['SIDEExplicitFormula.Chi.ZetaBoundsStrip', 'SIDEExplicitFormula.Chi.Statement'],
        title='GRH-Weil act three: the representation of L(s, χ) on the strip, ZetaBounds` analogue, EF_lit_chi stated '
              '(act b567, ruling (R177)(6))',
        consumed=['DirichletCharacter.LFunction_eq_LSeries', 'LSeries_eq_mul_integral', 'mellin_differentiableAt_of_isBigO_rpow',
                  'mellin_hasDerivAt_of_isBigO_rpow', 'AnalyticOnNhd.eqOn_of_preconnected_of_eventuallyEq',
                  'sum_mul_eq_sub_sub_integral_mul\'', 'SIDEExplicitFormula.GRHWeil.norm_charPartialSum_le'],
        check=[]),
}


def main(argv):
    which = argv[0] if argv else ''
    if which not in SETS:
        print(__doc__)
        return 2
    c = SETS[which]
    decls = []
    for rel, ns in c['files']:
        t = subprocess.run(['git', '-C', EF, 'show', c['rev'] + ':' + rel], capture_output=True).stdout.decode('utf-8')
        if not t:
            print('### %s IS NOT AT THE TIP OF %s: skipped' % (rel, c['rev']))
            continue
        decls += [dict(file=rel, kind='theorem' if m.group(1) == 'theorem' else 'def', name=ns + m.group(2),
                       line=t.count(NL, 0, m.start()) + 1) for m in DECL.finditer(t)]
    if not decls:
        print('### NO DECLARATION READ: refusing')
        return 2
    imports = [i for i, (rel, _) in zip(c['imports'], c['files'])
               if subprocess.run(['git', '-C', EF, 'cat-file', '-e', c['rev'] + ':' + rel]).returncode == 0]
    src = ['import ' + i for i in imports] + ['', '/-!', '# Axiom audit -- ' + c['title'], '',
           'Run `lake env lean %s` (once the modules are built) to reproduce the `#print axioms` output for every' % c['out'],
           'declaration of the files below and for the terminals they consume by name, the `#check` of the named statements, and',
           'the `#print` of each definition (the salt-check). Each is expected to reduce to the standard base (`propext`,',
           '`Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output is the verdict, not this comment.',
           'GENERATED by relay tools/b567_axiomcheck_gen.py from the tip of %s.' % c['rev'], '-/', '']
    src += ['#print axioms %s' % d['name'] for d in decls]
    src += [''] + ['#print axioms %s' % n for n in c['consumed']]
    names = c['check'] or [d['name'] for d in decls if d['kind'] == 'theorem']
    src += [''] + ['#check @%s' % n for n in names]
    src += [''] + ['#print %s' % d['name'] for d in decls if d['kind'] == 'def']
    io.open(os.path.join(EF, c['out']), 'w', encoding='utf-8', newline=NL).write(NL.join(src) + NL)
    json.dump(dict(rev=c['rev'], decls=decls, consumed=c['consumed'], out=c['out']),
              io.open(os.path.join(D, 'b567_decls_%s.json' % which), 'w', encoding='utf-8', newline=NL), ensure_ascii=False, indent=1)
    print('%s: declarations %d (theorems %d, defs %d) ; consumed %d' % (c['out'], len(decls), sum(d['kind'] == 'theorem' for d in decls),
                                                                      sum(d['kind'] == 'def' for d in decls), len(c['consumed'])))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
