# -*- coding: utf-8 -*-
"""b569_axiomcheck_gen.py -- READINGS (3) AND (7): AN AxiomCheck FILE GENERATED FROM A BRANCH TIP'S OWN FILES.
### `python tools/b569_axiomcheck_gen.py converses` -> AxiomCheckConverses.lean (PageConverses.lean at grh-weil-b569);
### `python tools/b569_axiomcheck_gen.py chi`       -> AxiomCheckChiRoute.lean (the seven Chi route modules at grh-weil-b569). Every declaration of the files (a regex over the file AT THE BRANCH'S COMMITTED TIP, never the working
### tree), then the terminals they consume by name, the `#check` of the named statements and the `#print` of each definition.
### Writes the one kernel file in the checkout and relay data/b569_decls_<which>.json. Deletes nothing.
"""
import io, json, os, re, subprocess, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, 'data')
EF = os.path.join('D:' + os.sep, 'SIDE-explicit-formula')
NL = chr(10)
DECL = re.compile(r'^(theorem|def|noncomputable def|abbrev)\s+([^\s(:{\[]+)', re.M)
CHI = ['ZetaGrowth', 'LocalCount', 'ZeroSummability', 'XiLogDeriv', 'CountByIntegral', 'Landau', 'GoodHeights']
SETS = {
    'converses': dict(
        rev='grh-weil-b569', out='AxiomCheckConverses.lean',
        files=[('SIDEExplicitFormula/PageConverses.lean', 'SIDEExplicitFormula.PageConverses.')],
        imports=['SIDEExplicitFormula.PageConverses'],
        title='the two converses the page lacked (act b569, ruling (R179)(2))',
        consumed=['SIDEExplicitFormula.LiWeil.rh_imp_li_nonneg', 'SIDEExplicitFormula.ResidueDischarge.register4_positivity_liCoeff_imp_rh',
                  'SIDEExplicitFormula.LiCriterionBridge.li_coeff_eq_taylorCoeff', 'LiCriterion.positivity_implies_RH',
                  'LiCriterion.rh_equiv_mathlib'],
        check=[]),
    'chi': dict(
        rev='grh-weil-b569', out='AxiomCheckChiRoute.lean',
        files=[('SIDEExplicitFormula/Chi/%s.lean' % m, 'SIDEExplicitFormula.GRHWeil.') for m in CHI],
        imports=['SIDEExplicitFormula.Chi.%s' % m for m in CHI],
        title='GRH-Weil act four: the chi-analogues of EF_lit`s route from ZetaGrowth to GoodHeights (act b569, ruling (R179)(6))',
        consumed=['DirichletCharacter.LFunction_eq_LSeries', 'DirichletCharacter.IsPrimitive.completedLFunction_one_sub',
                  'Zeta23.WeilEF.EF_zero_sum_summable_gen', 'Zeta23.WeilEF.logDeriv_partial_fraction_disk', 'ZerosBound',
                  'SIDEExplicitFormula.GRHWeil.LFunction_eq_mul_integral', 'SIDEExplicitFormula.GRHWeil.norm_integral_tail_le'],
        check=[]),
}


def main(argv):
    which = argv[0] if argv else ''
    if which not in SETS:
        print(__doc__)
        return 2
    c = SETS[which]
    decls = []
    for rel, ns in c['files']:
        t = subprocess.run(['git', '-C', EF, 'show', c['rev'] + ':' + rel], capture_output=True).stdout.decode('utf-8')
        if not t:
            print('### %s IS NOT AT THE TIP OF %s: skipped' % (rel, c['rev']))
            continue
        decls += [dict(file=rel, kind='theorem' if m.group(1) == 'theorem' else 'def', name=ns + m.group(2),
                       line=t.count(NL, 0, m.start()) + 1) for m in DECL.finditer(t)]
    if not decls:
        print('### NO DECLARATION READ: refusing')
        return 2
    imports = [i for i, (rel, _) in zip(c['imports'], c['files'])
               if subprocess.run(['git', '-C', EF, 'cat-file', '-e', c['rev'] + ':' + rel]).returncode == 0]
    src = ['import ' + i for i in imports] + ['', '/-!', '# Axiom audit -- ' + c['title'], '',
           'Run `lake env lean %s` (once the modules are built) to reproduce the `#print axioms` output for every' % c['out'],
           'declaration of the files below and for the terminals they consume by name, the `#check` of the named statements, and',
           'the `#print` of each definition (the salt-check). Each is expected to reduce to the standard base (`propext`,',
           '`Classical.choice`, `Quot.sound`) or less, with no `sorryAx`. The compiler`s output is the verdict, not this comment.',
           'GENERATED by relay tools/b569_axiomcheck_gen.py from the tip of %s.' % c['rev'], '-/', '']
    src += ['#print axioms %s' % d['name'] for d in decls]
    src += [''] + ['#print axioms %s' % n for n in c['consumed']]
    names = c['check'] or [d['name'] for d in decls if d['kind'] == 'theorem']
    src += [''] + ['#check @%s' % n for n in names]
    src += [''] + ['#print %s' % d['name'] for d in decls if d['kind'] == 'def']
    io.open(os.path.join(EF, c['out']), 'w', encoding='utf-8', newline=NL).write(NL.join(src) + NL)
    json.dump(dict(rev=c['rev'], decls=decls, consumed=c['consumed'], out=c['out']),
              io.open(os.path.join(D, 'b569_decls_%s.json' % which), 'w', encoding='utf-8', newline=NL), ensure_ascii=False, indent=1)
    print('%s: declarations %d (theorems %d, defs %d) ; consumed %d' % (c['out'], len(decls), sum(d['kind'] == 'theorem' for d in decls),
                                                                      sum(d['kind'] == 'def' for d in decls), len(c['consumed'])))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
