# -*- coding: utf-8 -*-
"""licensed_table.py -- THE LICENSED-STATEMENT TABLE, THE REVIEW PASS'S INSTRUMENT, written at b645 under (R255)(3).

### ONE ROW PER CLAIM, FIVE CELLS:
###   SOURCE   -- file and line (`path:N`), or kernel and declaration (`kernel@pin:Decl.name`);
###   STATED   -- the sentence or docstring as it reads;
###   LICENSED -- the statement the corpus now licenses, from the terminal table's grade, the premise table's statuses, the consumers print
###               and the census. GENERATED where a rule can generate it (a docstring against its declaration's elaborated statement and
###               grade: `docstring`; a claim naming a terminal against that terminal's row: `terminal`), its rule named in `by`; HAND
###               where the seat read it, with the lines read cited in `cited` (each `path:N`, `path:N-M` or `repo@pin:path:N`);
###   VERDICT  -- exactly one of MATCHES / UNDERSTATES / OVERREACHES / UNLICENSED (a claim no kernel and no citation reaches);
###   ACTION   -- for MATCHES `none`; for UNDERSTATES or OVERREACHES `RE-CUT: <the sentence proposed>` or a named work-order with a
###               trigger (`W-ORD-<NAME>, TRIGGER <when>`) where the repair needs a build; for UNLICENSED a work-order or
###               `RETIRE TO ERRATA: <why>`.
### `check(row)` returns the row's faults (an empty list is a row the table takes); `table(rows)` refuses the whole table when any row has
### a fault and returns the counts by verdict -- the pass's findings. A HAND row without a citation is refused.
### The rules are printed by `rules()` before a run reads a real row.
"""
import collections
import re

VERDICTS = ('MATCHES', 'UNDERSTATES', 'OVERREACHES', 'UNLICENSED')
CELLS = ('source', 'stated', 'licensed', 'verdict', 'action')
CITE_RE = re.compile(r'^(?:[\w.\-]+@[0-9a-f]{6,40}:)?[\w./\-]+(?:\.\w+)?:\d+(?:-\d+)?$')
SOURCE_RE = re.compile(r'^(?:[\w.\-]+@[0-9a-f]{6,40}:[\w.\'’!?₀-₉]+|[\w./\-]+\.\w+:\d+(?:-\d+)?)$')
RULES = {
    'docstring': 'the docstring against its declaration`s elaborated statement (relay data/b643_elab_ef.txt) and its grade in the terminal '
                 'table, and every grade word it attaches to a named declaration against that declaration`s row',
    'module': 'a module`s header block: every grade word it attaches to a named declaration against that declaration`s row',
    'terminal': 'a claim naming a terminal against that terminal`s row in the terminal table (grade, statement, profile) and, for a premise, '
                'its status in the premise table',
    'intake': 'a claim of a document through the intake form of b628 (its grade, its route, its terminal), its outcome mapped to a verdict by '
              'the mapping printed before the run',
}


def check(row):
    """the row's faults: [] when the table takes it."""
    f = []
    for c in CELLS:
        if not isinstance(row.get(c), str) or not row[c].strip():
            f.append('cell %s empty' % c)
    v = row.get('verdict')
    if v not in VERDICTS:
        f.append('verdict %r not one of the four' % (v,))
    if not SOURCE_RE.match(str(row.get('source', ''))):
        f.append('source %r is neither path:line nor kernel@pin:declaration' % (row.get('source'),))
    by = row.get('by')
    if by == 'HAND':
        cites = row.get('cited') or []
        if not cites:
            f.append('HAND row without a citation of the lines read')
        bad = [c for c in cites if not CITE_RE.match(c)]
        if bad:
            f.append('HAND citations not of the form path:N: %s' % bad)
    elif by not in RULES:
        f.append('LICENSED neither HAND nor generated by a named rule (%r)' % (by,))
    if row.get('hand_needed') and by != 'HAND':
        f.append('a generated row the rule flags for a hand reading (%s) has none' % row['hand_needed'][:60])
    a = str(row.get('action', ''))
    if v == 'MATCHES' and a != 'none':
        f.append('MATCHES carries an action')
    if v in ('UNDERSTATES', 'OVERREACHES') and not (a.startswith('RE-CUT: ') and len(a) > 12 or re.match(r'^W-ORD-[A-Z0-9-]+, TRIGGER \S', a)):
        f.append('%s without a re-cut sentence or a work-order with a trigger' % v)
    if v == 'UNLICENSED' and not (re.match(r'^W-ORD-[A-Z0-9-]+, TRIGGER \S', a) or a.startswith('RETIRE TO ERRATA: ')):
        f.append('UNLICENSED without a work-order or a retirement to ERRATA')
    return f


def table(rows):
    """(counts by verdict, faults by row id); the table is refused -- counts None -- when any row has a fault."""
    faults = dict((r.get('id', '#%d' % i), check(r)) for i, r in enumerate(rows))
    faults = dict((k, v) for k, v in faults.items() if v)
    ids = [r.get('id') for r in rows]
    dup = [k for k, n in collections.Counter(ids).items() if n > 1]
    if dup:
        faults['duplicate ids'] = dup
    if faults:
        return None, faults
    c = collections.OrderedDict((v, 0) for v in VERDICTS)
    for r in rows:
        c[r['verdict']] += 1
    return c, {}


# ================================================================================ THE GRADE WORDS AND THEIR ORDER
# ### the claim a sentence attaches to a name, strongest first; a claim above the row's grade OVERREACHES, below it UNDERSTATES
STRENGTH = {'DERIVES': 3, 'DISCHARGED': 3, 'WITNESSED': 3, 'INTERFACES': 2, 'CITED': 2, 'OPEN': 1, 'DEF': 0, 'DOMAIN': 0}
CLAIM_WORDS = [
    (re.compile(r'(?:\b(?:NOT|not|never|NEVER) (?:yet )?(?:PROVED|proved|compiled|COMPILED)\b|\bunproved\b|\bUNPROVED\b)'), 'OPEN'),
    (re.compile(r'(?<!NOT )(?<!not )(?<!yet )\b(?:PROVED|proved|proves|DERIVES|derives (?:it|them)? ?(?:outright|unconditionally)|'
                r'holds unconditionally|unconditionally|no hypothesis|without hypothesis|outright|compiled|inhabited|closed)\b'), 'DERIVES'),
    (re.compile(r'\b(?:INTERFACES|at INTERFACES|on (?:its|the|two|one|three) (?:named )?(?:premise|premises|obligation|obligations|hypothesis)|'
                r'under (?:its|the|two|one) (?:named )?(?:premise|premises|obligations?|hypothes[ie]s)|CARRIED TO|carried to)\b'), 'INTERFACES'),
    (re.compile(r'\b(?:OPEN|is open|stays open|remains open|not (?:yet )?(?:compiled|proved)|unproved|conjectur\w*)\b'), 'OPEN'),
]
UNCOND = re.compile(r'\b(?:unconditionally|no hypothesis|without (?:any )?hypothes[ie]s|outright|for every [^.;]{0,40} with no premise)\b')
MATHLIB_SCOPE = re.compile(r'(?:\bno Mathlib\b|\bnot in Mathlib\b|\bMathlib-absent\b|\babsent from Mathlib\b|\bABSENT from Mathlib\b|'
                           r'\bMathlib\b[^.;]{0,40}?\b(?:does not (?:hold|have|carry|state)|lacks|has no|holds [^.;]{0,60}?(?<!and )only)\b|'
                           r'\bonly for [A-Za-z]+ functions\b|\bfor [A-Z][a-z]+ functions only\b)')
EQUIV = re.compile(r'\b(?:equivalen(?:t|ce)|if and only if|both directions|iff)\b|↔')
OPENSELF = re.compile(r'\b(?:this (?:is|stays|remains) (?:open|conditional)|is assumed here|not (?:yet )?(?:compiled|proved) here)\b')


def names_in(text, plain=False):
    """the backticked identifiers of a docstring and the position of each; with `plain`, also every bare identifier that carries an
    underscore or a dot (a declaration's shape), left for the lookup to resolve or drop."""
    out = []
    for m in re.finditer(r'`([A-Za-z_][\w.\'’!?₀-₉]*)`', text):
        out.append((m.group(1), m.start(), m.end()))
    if plain:
        taken = set(range(0, 0))
        for _n, s, e in out:
            taken |= set(range(s, e))
        for m in re.finditer(r'(?<![`\w.])([A-Za-z][\w\']*(?:[._][\w\']+)+)(?![`\w])', text):
            if m.start() not in taken and not re.match(r'^\w+\.lean$', m.group(1)):
                out.append((m.group(1), m.start(), m.end()))
    return out


def attached_claims(text, window=90, plain=False):
    """(name, claimed grade, the words) for every grade word within one clause after a named identifier, or before it in the same clause.
    The clause is cut at `;`, `.` followed by a space, or a new bullet."""
    out = []
    for name, s, e in names_in(text, plain):
        after = re.split(r'[;\n]|\. |\* ', text[e:e + window])[0]
        before = re.split(r'[;\n]|\. |\* ', text[max(0, s - window):s])[-1]
        for rx, gname in CLAIM_WORDS:
            m = rx.search(after)
            side = 'after'
            if not m:
                m, side = rx.search(before), 'before'
            if m:
                out.append((name, gname, m.group(0), side))
                break
    return out


def compare(claimed, actual):
    """the verdict of one claim against one row's grade: MATCHES, OVERREACHES (claims more) or UNDERSTATES (claims less); None when the
    row's grade is not on the strength scale (CONFLICT, '—', UNGRADED, PREDICATE-UNLISTED counted as INTERFACES)."""
    a = {'PREDICATE-UNLISTED': 'INTERFACES', 'ENCODES-CONCLUSION': 'INTERFACES'}.get(actual, actual)
    if a not in STRENGTH or claimed not in STRENGTH:
        return None
    if a == 'DEF':
        return 'MATCHES' if claimed in ('DEF', 'DERIVES') else None
    d = STRENGTH[claimed] - STRENGTH[a]
    return 'MATCHES' if d == 0 else ('OVERREACHES' if d > 0 else 'UNDERSTATES')


def worst(verdicts):
    for v in ('UNLICENSED', 'OVERREACHES', 'UNDERSTATES'):
        if v in verdicts:
            return v
    return 'MATCHES'


PREMISE_OPEN = {'DISCHARGED': 'UNDERSTATES', 'WITNESSED': 'UNDERSTATES'}
PREMISE_DONE = {'OPEN': 'OVERREACHES', 'CITED': 'OVERREACHES', 'REFUTED-BY-COMPUTATION': 'OVERREACHES'}


OPENWORD = re.compile(r'\b(?:NOT PROVED|not proved|not yet proved|NOT COMPILED|not compiled|unproved|UNPROVED|is open|stays open|remains open|'
                      r'OPEN)\b')


def docstring_row(rid, source, doc, decl, kind, statement, grade, provenance, premises, lookup, module=False, status=None, proved_by=None):
    """the generated row of one docstring: LICENSED from the elaborated statement and the grade; the verdict by `docstring` (or `module`)
    -- (D1) its own scope: an unconditional marker on a declaration graded INTERFACES OVERREACHES, an open-or-conditional marker about
    itself on one graded DERIVES with no premise UNDERSTATES; (D2) every proof, interface or open word it attaches to a named declaration
    (backticked, or bare where the lookup resolves it), against that declaration's row (`lookup(name)` -> (qualified name, grade) or None) --
    an open word is read against a theorem's grade only when it follows the name in its clause (the name its subject; b645's PairTerm read:
    "NOT PROVED (`farSmall`, `pair_bound`)" names a hypothesis, not the bound); (D3) every open or proof word it attaches to a premise head, against the head's status in the
    premise table (`status(name)` -> status or None): a DISCHARGED or WITNESSED head called open UNDERSTATES, an OPEN, CITED or refuted head
    called proved OVERREACHES. The ACTION names each finding; the re-cut sentence is the seat's, written when the row is read whole (`recut`)."""
    found = []
    if not module and decl:
        first = re.split(r'(?<=[.:])\s', doc.strip(), maxsplit=1)[0]
        eq = EQUIV.search(first)
        if eq and kind in ('theorem', 'lemma') and '↔' not in statement and 'Iff' not in statement:
            found.append(('OVERREACHES', 'D4: its first sentence claims an equivalence (%r) while the elaborated statement holds no ↔: %s' % (
                eq.group(0), statement[-160:])))
        # ### (D6) a definition of a Prop its docstring calls unproved or open, while a theorem of the kernel with no binder concludes
        # ### exactly that Prop (`proved_by(decl)` -> the theorem's name and line, or None): the docstring says less than the kernel holds
        ow = OPENWORD.search(first)
        pb = proved_by(decl) if (proved_by and kind in ('def', 'abbrev') and ow) else None
        if pb:
            found.append(('UNDERSTATES', 'D6: the Prop is called %r while the kernel proves it: %s' % (ow.group(0), pb)))
        if grade in ('INTERFACES', 'PREDICATE-UNLISTED') and UNCOND.search(doc):
            found.append(('OVERREACHES', 'D1: calls the result unconditional (%r) while it is graded %s on %s' % (
                UNCOND.search(doc).group(0), grade, ', '.join(premises) or 'its premise')))
        if grade == 'DERIVES' and not premises and OPENSELF.search(doc):
            found.append(('UNDERSTATES', 'D1: calls itself %r while it is graded DERIVES with no premise' % OPENSELF.search(doc).group(0)))
    seen = set()
    for name, claimed, words, side in attached_claims(doc, plain=True):
        if (name, claimed) in seen:
            continue
        seen.add((name, claimed))
        st = status(name.split('.')[-1]) if status else None
        if st:
            v = (PREMISE_OPEN.get(st) if claimed == 'OPEN' else PREMISE_DONE.get(st) if claimed == 'DERIVES' else None)
            if v:
                found.append((v, 'D3: premise `%s` called %s (%r) while its status is %s' % (name, claimed, words, st)))
            continue
        hit = lookup(name)
        if not hit or (claimed == 'OPEN' and side == 'before'):
            continue
        qn, g = hit
        v = compare(claimed, g)
        if v in ('OVERREACHES', 'UNDERSTATES'):
            found.append((v, 'D2: `%s` called %s (%r) while its row reads %s' % (name, claimed, words, g)))
    v = worst([x[0] for x in found])
    lic = ('%s %s : %s -- grade %s (%s)%s' % (kind, decl, statement, grade, provenance, ('; premises: ' + ', '.join(premises)) if premises else '')
           if decl else 'the module`s declarations, each at its row: ' + statement)
    # ### (D5) THE PLATEAURAMP SHAPE, GENERALISED (OPEN_TRAILS :13491): a claim about what Mathlib at the pin holds -- an absence, or a scope
    # ### narrower than a class -- is a claim about a cited library no rule over the kernel's own statement can read; the row is flagged
    # ### HAND-NEEDED and the table refuses it until the seat reads Mathlib at the pin and writes the row by hand, citing the lines read.
    sc = [m.group(0) for m in MATHLIB_SCOPE.finditer(doc)]
    row = dict(id=rid, source=source, stated=doc, licensed=lic, by='module' if module else 'docstring', verdict=v,
               action='none' if v == 'MATCHES' else 'PENDING-RECUT', findings=[x[1] for x in found])
    if sc:
        row['hand_needed'] = 'D5: a claim about Mathlib at the pin (%s), read by hand against Mathlib at the pin' % '; '.join(repr(x) for x in sc)
        row['findings'].append(row['hand_needed'])
    return row


def terminal_row(rid, source, stated, name, claimed, lookup):
    """the generated row of a claim naming a terminal with a grade (`claimed`, a word of STRENGTH): LICENSED from the terminal's row
    (`lookup(name)` -> (qualified name, grade, statement, pin)); the verdict by `terminal`; None when the name has no row (the row is then
    read by hand)."""
    hit = lookup(name)
    if not hit:
        return None
    qn, g, st, pin = hit
    v = compare(claimed, g)
    if v is None:
        return None
    return dict(id=rid, source=source, stated=stated, licensed='%s at %s : %s -- grade %s' % (qn, pin, st, g), by='terminal', verdict=v,
                action='none' if v == 'MATCHES' else 'PENDING-RECUT', findings=[] if v == 'MATCHES' else ['T: `%s` claimed %s, its row reads %s' % (name, claimed, g)])


def recut(row, sentence):
    """the seat's re-cut sentence for a generated UNDERSTATES or OVERREACHES row."""
    row = dict(row)
    row['action'] = 'RE-CUT: ' + sentence
    return row


# ================================================================================ THE INTAKE MAPPING ((R255)(4)(d))
# ### the intake form's outcome (grade, how the claim is stated, route verdict) to the table's verdict, printed before the run
STATED_AS = ('established', 'graded', 'open', 'less')   # ### how the sentence states its claim: as established fact / at its own grade /
#                                                         ### as open or conjectural / saying less than the corpus licenses
MAPPING = [
    ('kernel-verified', 'established', 'MATCHES', 'the terminal at its pin carries the claim as stated'),
    ('kernel-verified', 'graded', 'MATCHES', 'the claim names its terminal and grade'),
    ('kernel-verified', 'over', 'OVERREACHES', 'the claim states more than its terminal carries (a stipulation read as content, a premise left unnamed)'),
    ('theorem-supported', 'established', 'OVERREACHES', 'a classical theorem cited as the programme`s compiled or proved result'),
    ('theorem-supported', 'graded', 'MATCHES', 'cited at its source as a classical theorem'),
    ('argument-supported', 'established', 'OVERREACHES', 'an argument of the document stated as proved or machine-checked'),
    ('argument-supported', 'graded', 'MATCHES', 'stated as the document`s argument, not as a compiled result'),
    ('computationally-verified', 'established', 'MATCHES', 'a computation stated as a computation'),
    ('computationally-verified', 'over', 'OVERREACHES', 'a finite computation stated as a general theorem'),
    ('synthesis-suggested', 'established', 'OVERREACHES', 'a synthesis reading stated as a result'),
    ('synthesis-suggested', 'graded', 'MATCHES', 'stated as a reading, interpretation or programme'),
    ('statement-grade', 'established', 'UNLICENSED', 'asserted as established; no kernel and no citation reaches it'),
    ('statement-grade', 'open', 'MATCHES', 'stated as open, conjectural or a definition of the document`s own terms'),
    ('any', 'less', 'UNDERSTATES', 'the corpus now licenses more than the sentence says (a compiled theorem called open, a terminal said not to exist)'),
    ('route DARK', 'established', 'OVERREACHES', 'a route offered as reaching its conclusion, which the sieve reads DARK'),
]


def map_intake(grade, stated_as, route_verdict='NOT A ROUTE'):
    """the verdict of one intake claim by MAPPING; raises when the pair is not in the mapping (the run stops, nothing guessed)."""
    if stated_as == 'less':
        return 'UNDERSTATES'
    if route_verdict == 'DARK' and stated_as == 'established':
        return 'OVERREACHES'
    for g, s, v, _why in MAPPING:
        if g == grade and s == stated_as:
            return v
    raise KeyError('no mapping for (%s, %s, %s)' % (grade, stated_as, route_verdict))


# ================================================================================ THE CENSUS'S THREE COLUMNS ((R255)(5)), DEFINED FOR v0.8
CLUSTERS = ('reduction-chain', 'h2-positivity', 'simplicity', 'surround', 'GRH-cascade', 'instances', 'method', 'side')
# ### the path rule, first match wins: (regex over the keystone's path, cluster)
PATH_RULES = [
    (r'(^|/)phase1\.5/simplicity/|SIMPLICITY', 'simplicity'),
    (r'GRH', 'GRH-cascade'),
    (r'SURROUND', 'surround'),
    (r'BALANCE_AND_POSITIVITY|POSITIVITY|FACES_OF_H2', 'h2-positivity'),
    (r'INSTANCE|DIRICHLET|EPSTEIN|DEDEKIND', 'instances'),
    (r'(^|/)day1/|(^|/)phase1\.5/proofs/|(^|/)phase1\.5/rcurve/', 'reduction-chain'),
    (r'(^|/)phase1\.5/method/|(^|/)phase2/method/|(^|/)phase2/formation/', 'method'),
    (r'(^|/)phase2/|(^|/)clusters/|(^|/)internal/|(^|/)heritage/|(^|/)phase1\.5/deep-structure/|(^|/)phase1\.5/structural/', 'side'),
]
# ### the terminal rule, where no path rule matches: the cluster whose terminals the keystone names most, by at least two names and alone
TERMINAL_SETS = {
    'reduction-chain': {'h2_sign_iff_rh', 'rh_strip_imp_rh_holds', 'ch_iff_rh', 'b321_identity', 'h2_sign_imp_rh_holds', 'ch_iff_h2_sign'},
    'h2-positivity': {'li_nonneg_iff_rh', 'partialPositivity_finiteRange', 'register4_positivity_liCoeff_iff_rh', 'liCoeff_one_pos',
                      'blTerm_nonneg_of_onLine', 'taylorCoeff_nonneg_iff_rh'},
    'simplicity': {'simplicity_iff', 'exceptional_mass_le_third', 'allSimple', 'positivity_not_imp_simplicity'},
    'surround': {'h1_complete_at_Phi', 'C7_finite_type_false', 'exists_norm_completedRiemannZeta₀_le_exp'},
    'GRH-cascade': {'h2_sign_chi_iff_grh_chi', 'GRH_chi', 'grh_chi_imp_h2_sign_chi', 'EF_lit_chi_holds'},
    'instances': {'family_theorem', 'dedekind_instance', 'epstein_detector', 'epstein_ef_at_window', 'detector'},
}


def cluster(path, names=()):
    """(cluster, how): the path rule first; else the terminal rule over the names the keystone carries; else ('', 'HAND')."""
    for rx, c in PATH_RULES:
        if re.search(rx, path):
            return c, 'path: %s' % rx
    cnt = collections.Counter()
    for c, s in TERMINAL_SETS.items():
        cnt[c] = len(s & set(names))
    best = cnt.most_common(2)
    if best and best[0][1] >= 2 and (len(best) == 1 or best[0][1] > best[1][1]):
        return best[0][0], 'terminals: %s' % dict((k, v) for k, v in cnt.items() if v)
    return '', 'HAND'


MATURITY = ('SETTLED', 'CARRIED-OPENLY', 'ONGOING', 'SUPERSEDED')
MATURITY_RULE = ('SUPERSEDED where the REGISTRY marks the keystone superseded by a later edition; else ONGOING where its table rows carry '
                 'any OVERREACHES or UNLICENSED (claims the kernels do not yet license); else CARRIED-OPENLY where any row states a frontier '
                 'as open (a claim stated as open, or a theorem at INTERFACES on a premise whose status is OPEN); else SETTLED (definitions '
                 'and compiled statements). UNDERSTATES does not move a keystone: it says less than the corpus licenses. A keystone no table '
                 'reaches is left blank and marked NOT YET IN THE TABLE, and no blank is counted as a value.')


def maturity(counts, open_rows=0, superseded=False):
    """the maturity of one keystone from its rows' verdict counts and its open-stated rows, by MATURITY_RULE; None counts -> blank."""
    if counts is None:
        return '', 'NOT YET IN THE TABLE'
    if superseded:
        return 'SUPERSEDED', 'the REGISTRY marks it superseded'
    if counts.get('OVERREACHES', 0) + counts.get('UNLICENSED', 0):
        return 'ONGOING', 'OVERREACHES %d, UNLICENSED %d' % (counts.get('OVERREACHES', 0), counts.get('UNLICENSED', 0))
    if open_rows:
        return 'CARRIED-OPENLY', '%d rows state a frontier as open' % open_rows
    return 'SETTLED', 'every row MATCHES or UNDERSTATES and none states a frontier open'


def rules():
    """the rules and the mapping, printed before any real row is read."""
    L = ['### THE LICENSED-STATEMENT TABLE`S RULES (tools/licensed_table.py), printed before the run:', '']
    L += ['  %-10s %s' % (k, v) for k, v in RULES.items()]
    L += ['', '### THE VERDICTS: ' + ' / '.join(VERDICTS),
          '### THE GRADE SCALE FOR A CLAIM ATTACHED TO A NAME: ' + ' ; '.join('%s %d' % kv for kv in STRENGTH.items()),
          '### (D1) unconditional markers: %s' % UNCOND.pattern, '### (D1) open-about-itself markers: %s' % OPENSELF.pattern,
          '### (D2) the claim words, strongest first:'] + ['    %s <- %s' % (g, rx.pattern[:200]) for rx, g in CLAIM_WORDS]
    L += ['', '### THE INTAKE MAPPING ((R255)(4)(d)), (grade, stated as) -> verdict:'] + [
        '    %-26s %-12s -> %-12s %s' % m for m in MAPPING]
    L += ['', '### THE CENSUS`S COLUMNS ((R255)(5)): CLUSTER one of %s -- the path rule first (first match wins):' % ', '.join(CLUSTERS)] + [
        '    %-12s <- %s' % (c, rx) for rx, c in PATH_RULES] + [
        '  then the terminal rule (the cluster whose terminals the keystone names most, by at least two and alone):'] + [
        '    %-15s %s' % (c, ', '.join(sorted(s))) for c, s in TERMINAL_SETS.items()] + [
        '  else HAND, with the lines read cited. PHASE: the phase of the REGISTRY heading the keystone`s row sits under, a field.',
        '### MATURITY, one of %s: %s' % (', '.join(MATURITY), MATURITY_RULE)]
    return L
